Repository kornia/kornia, pull requests merged in 2019-10, with the labels that each got.

#222 [ready to review] local feature detection rebased
  docs/source/contrib.rst
  docs/source/feature.rst
  docs/source/geometry.conversions.rst
  docs/source/geometry.rst
  docs/source/references.bib
  examples/feature_detection/extract_local_patches.ipynb
  examples/feature_detection/img/graffiti.png
  examples/feature_detection/img/kpi_winter.png
  examples/feature_detection/img/siemens.png
  examples/feature_detection/local_feature_detection_example.ipynb
  kornia/__init__.py
  kornia/contrib/__init__.py
  kornia/contrib/spatial_soft_argmax2d.py
  kornia/feature/__init__.py
  kornia/feature/affine_shape.py
  kornia/feature/harris.py
  kornia/feature/laf.py
  kornia/feature/orientation.py
  kornia/feature/responses.py
  kornia/feature/scale_space_detector.py
  kornia/feature/siftdesc.py
  kornia/filters/sobel.py
  kornia/geometry/__init__.py
  kornia/geometry/conversions.py
  kornia/geometry/dsnt.py
  kornia/geometry/spatial_soft_argmax.py
  kornia/geometry/transform/pyramid.py
  kornia/utils/__init__.py
  kornia/utils/grid.py
  mypy_files.txt
  setup.cfg
  test/feature/test_affine_shape_estimator.py
  test/feature/test_harris.py
  test/feature/test_laf.py
  test/feature/test_local_features_orientation.py
  test/feature/test_responces_local_features.py
  test/feature/test_scale_space_detector.py
  test/geometry/test_spatial_softargmax.py
  test/integration/test_soft_argmax2d.py
  test/test_contrib.py
  tox.ini
Labels: high priority

#234 Feat/color
  docs/source/color.rst
  kornia/__init__.py
  kornia/color/__init__.py
  kornia/color/adjust.py
  scripts/build_wheel.sh
  test/color/test_adjust.py
Labels: PR: Needs Review, high priority

#249 Fix typo in color files
  kornia/color/gray.py
  kornia/color/hsv.py
  kornia/color/rgb.py
Labels: PR: Good to Merge

#242 Update faqs.rst
  docs/source/faqs.rst
Labels: PR: Good to Merge

#250 Ananyamukh6/total variation
  docs/source/losses.rst
  examples/total_variation_denoising.py
  kornia/__init__.py
  kornia/filters/filter.py
  kornia/losses/__init__.py
  kornia/losses/total_variation.py
  test/test_losses.py
Labels: PR: Good to Merge

#254 Added boundary check function to local features detector
  examples/feature_detection/local-feature-adversarial-attack.ipynb
  examples/feature_detection/local_feature_detection_example.ipynb
  kornia/feature/__init__.py
  kornia/feature/laf.py
  kornia/feature/scale_space_detector.py
  test/feature/test_laf.py
Labels: PR: Good to Merge

#258 add reference to pytorch discuss in contributing
  CONTRIBUTING.rst
Labels: docs

#253 Feat/hls
  docs/source/color.rst
  kornia/__init__.py
  kornia/color/__init__.py
  kornia/color/hls.py
  test/color/test_hls.py
Labels: PR: Good to Merge

#259 update to pytorch 1.3 and fix small test issues
  requirements.txt
  test/geometry/test_pinhole.py
  test/geometry/warp/test_homography_warper.py
Labels: enhancement

#268 Flips
  docs/source/geometry.transform.rst
  kornia/geometry/transform/__init__.py
  kornia/geometry/transform/flips.py
  test/geometry/transform/test_flip.py
Labels: PR: Good to Merge

#285 setup env os bug
  setup_dev_env.sh
Labels: PR: Good to Merge

#272 Ananyamukh6/psnr
  docs/source/losses.rst
  kornia/__init__.py
  kornia/losses/__init__.py
  kornia/losses/psnr.py
  kornia/losses/total_variation.py
  test/test_losses.py
Labels: PR: Needs Review

#291 changed type hints from np.array to np.ndarray
  examples/color_adjust.py
  examples/color_conversions.py
  examples/filter_blurring.py
  examples/filter_edges.py
  examples/gaussian_blur.py
  examples/hello_world.py
  examples/total_variation_denoising.py
  examples/warp_affine.py
  examples/warp_perspective.py
Labels: PR: Needs Review

#295 [Feature] AddWeighted
  docs/source/color.rst
  kornia/color/__init__.py
  kornia/color/core.py
  test/color/test_core.py
Labels: PR: Needs Review

#301 Single value support for normalize function
  kornia/color/normalize.py
  test/color/test_normalize.py
Labels: PR: Good to Merge

#303 fix documentation of angle_axis_to_rotation_matrix
  kornia/geometry/conversions.py
Labels: PR: Good to Merge

#305 Correct crop_and_resize on aspect ratio changes.
  kornia/geometry/transform/crop.py
  test/geometry/transform/test_crop.py
Labels: PR: Good to Merge

#304 Correct adjust brightness and contrast
  kornia/color/adjust.py
  kornia/geometry/transform/flips.py
  test/color/test_adjust.py
  test/geometry/transform/test_flip.py
Labels: PR: Good to Merge
