Repository kornia/kornia, pull requests merged in 2019-08, with the labels that each got.

#204 [ready to review] Normalized version of filters + __repr__
  .coveragerc
  kornia/filters/blur.py
  kornia/filters/filter.py
  kornia/filters/gaussian.py
  kornia/filters/kernels.py
  kornia/filters/laplacian.py
  kornia/filters/sobel.py
  setup.cfg
  test/filters/test_filters.py
  test/filters/test_sobel.py
Labels: high priority

#183 [ready to review] SIFT descriptor as in https://github.com/ducha-aiki/pytorch-sift
  kornia/__init__.py
  kornia/feature/__init__.py
  kornia/feature/siftdesc.py
  kornia/filters/kernels.py
  test/feature/test_siftdesc.py
Labels: high priority

#167 Add DSNT operations to contrib
  kornia/contrib/dsnt.py
  kornia/contrib/spatial_soft_argmax2d.py
  kornia/losses/__init__.py
  kornia/losses/divergence.py
  test/test_contrib.py
  test/test_losses.py
Labels: PR: Needs Review, high priority

#206 Cleaned version of [ Basic functionality to work with local features]
  examples/feature_detection/extract_local_patches.ipynb
  examples/feature_detection/img/prague.hesaffnet
  examples/feature_detection/img/prague.png
  kornia/feature/__init__.py
  kornia/feature/laf.py
  kornia/feature/siftdesc.py
  kornia/geometry/transform/imgwarp.py
  test/feature/test_laf.py
Labels: PR: Needs Response, high priority
