Repository kornia/kornia, pull requests merged in 2019-12, with the labels that each got.

#364 Fix 363: *args to **kwargs in docs
  kornia/losses/focal.py
Labels: PR: Good to Merge

#362 fix typos in docs
  kornia/utils/image.py
Labels: PR: Good to Merge

#345 RGB <-> YCbCr
  kornia/__init__.py
  kornia/color/__init__.py
  kornia/color/gray.py
  kornia/color/hls.py
  kornia/color/hsv.py
  kornia/color/rgb.py
  kornia/color/ycbcr.py
  test/color/test_ycbcr.py
Labels: PR: Good to Merge

#344 Add Random (rectangle) erasing
  docs/source/augmentation.rst
  docs/source/filters.rst
  kornia/augmentation/__init__.py
  kornia/augmentation/random_erasing.py
  test/augmentation/test_augmentation.py
Labels: PR: Good to Merge

#369 add from homogeneous zero grad test and fix it
  kornia/geometry/conversions.py
  test/integration/test_warp.py
Labels: PR: Good to Merge, high priority

#361 small fix in grayscale conversion and add opencv tests
  kornia/color/gray.py
  test/color/test_gray.py
Labels: PR: Good to Merge

#373 Use latest version of CircleCI
  .circleci/config.yml
Labels: PR: Good to Merge

#377 Filter2d failed with noncontiguous input (view --> reshape)
  kornia/augmentation/random_erasing.py
  kornia/filters/filter.py
  kornia/filters/median.py
  test/filters/test_blur.py
  test/filters/test_filters.py
  test/filters/test_gaussian.py
  test/filters/test_median.py
  test/filters/test_motion.py
  test/filters/test_sobel.py
Labels: PR: Good to Merge

#378 fix horizontal flip width index access
  kornia/augmentation/augmentations.py
  test/augmentation/test_augmentation.py
Labels: PR: Good to Merge

#375 add `RandomVerticalFlip`
  docs/source/augmentation.rst
  kornia/__init__.py
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentations.py
  test/augmentation/test_augmentation.py
Labels: PR: Needs Review

#379 infer border and padding mode to homography warper
  kornia/geometry/transform/crop.py
  kornia/geometry/transform/imgwarp.py
Labels: PR: Needs Review

#383 apply normalization trick to conv_softmax
  kornia/geometry/spatial_soft_argmax.py
Labels: bug

#371 [ready to review] Better nms
  docs/source/feature.rst
  docs/source/filters.rst
  docs/source/geometry.rst
  examples/feature_detection/local_feature_detection_example.ipynb
  kornia/__init__.py
  kornia/feature/__init__.py
  kornia/feature/nms.py
  kornia/feature/responses.py
  kornia/feature/scale_space_detector.py
  kornia/filters/__init__.py
  kornia/filters/kernels.py
  kornia/filters/sobel.py
  kornia/geometry/spatial_soft_argmax.py
  kornia/geometry/transform/pyramid.py
  test/feature/test_nms.py
  test/feature/test_responces_local_features.py
  test/feature/test_scale_space_detector.py
  test/filters/test_sobel.py
  test/geometry/test_spatial_softargmax.py
  test/geometry/transform/test_pyramid.py
Labels: PR: Needs Review

#384 Random Grayscale
  docs/source/augmentation.rst
  kornia/__init__.py
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentations.py
  test/augmentation/test_augmentation.py
Labels: PR: Good to Merge
