Repository kornia/kornia, pull requests merged in 2020-04, with the labels that each got.

#498 [Feature] implement hardnet descriptor
  docs/source/feature.rst
  docs/source/references.bib
  kornia/feature/__init__.py
  kornia/feature/hardnet.py
  test/feature/test_hardnet.py
Labels: PR: Needs Review

#482 [Augmentation] Functional augmentation performance test against Torchvision
  docs/source/augmentation.rst
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/erasing.py
  kornia/augmentation/functional.py
  kornia/augmentation/random.py
  kornia/augmentation/types.py
  kornia/augmentation/utils.py
  kornia/color/adjust.py
  mypy_files.txt
  test/augmentation/test_augmentation.py
  test/augmentation/test_functional.py
  test/augmentation/test_param_gen.py
  test/augmentation/test_perspective.py
Labels: PR: Good to Merge

#511 [Depth] Add normalize_points flag
  kornia/geometry/camera/perspective.py
  kornia/geometry/depth.py
  test/geometry/test_depth.py
Labels: PR: Good to Merge

#512 remove PIL dependency
  kornia/utils/image.py
Labels: PR: Good to Merge

#513 [BUG] add epsilon value to sobel to improve backprop stability
  kornia/filters/sobel.py
  test/filters/test_sobel.py
Labels: PR: Needs Review

#514 [Feat] AffineTransformation alignment and other fixes
  kornia/__init__.py
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
  kornia/augmentation/random_generator.py
  kornia/augmentation/utils.py
  kornia/color/adjust.py
  kornia/color/hls.py
  kornia/color/hsv.py
  kornia/constants.py
  kornia/feature/laf.py
  kornia/feature/orientation.py
  kornia/geometry/conversions.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/crop.py
  kornia/geometry/transform/imgwarp.py
  kornia/losses/depth_smooth.py
  kornia/losses/dice.py
  kornia/losses/focal.py
  kornia/losses/ssim.py
  kornia/losses/tversky.py
  kornia/utils/metrics/confusion_matrix.py
  mypy_files.txt
  test/augmentation/test_augmentation.py
  test/augmentation/test_functional.py
  test/augmentation/test_perspective.py
  test/augmentation/test_random_generator.py
  test/color/test_adjust.py
  test/color/test_hls.py
  test/color/test_hsv.py
  test/geometry/transform/test_affine.py
Labels: PR: Good to Merge

#525 [DOCS] Fix simple typo in invert_affine_transform_matrix
  kornia/geometry/transform/imgwarp.py
Labels: PR: Good to Merge

#528 Lferraz kognia improve homography warper
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/warp/homography_warper.py
  test/geometry/warp/test_homography_warper.py
Labels: PR: Good to Merge

#531 Moves _check_and_bound to augmentation.utils
  kornia/augmentation/random_generator.py
  kornia/augmentation/utils.py
Labels: PR: Good to Merge

#534 Decoupled return_transform from apply_* function
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
  kornia/augmentation/types.py
  kornia/augmentation/utils.py
  kornia/geometry/transform/crop.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_functional.py
  test/augmentation/test_perspective.py
  test/augmentation/test_transformation_matrix.py
Labels: PR: Good to Merge

#542 [DOCS] reorganise documenation in subsections
  docs/source/augmentation.rst
  docs/source/color.rst
  docs/source/contrib.rst
  docs/source/feature.rst
  docs/source/filters.rst
  docs/source/geometry.rst
  docs/source/losses.rst
  docs/source/utils.metrics.rst
  docs/source/utils.rst
Labels: PR: Good to Merge

#538 [TESTS][GPU] fix broken gpu tests
  kornia/augmentation/functional.py
  requirements.txt
  test/color/test_gray.py
  test/color/test_ycbcr.py
  test/feature/test_scale_space_detector.py
  test/filters/test_sobel.py
  test/geometry/test_spatial_softargmax.py
  test/test_losses.py
Labels: PR: Good to Merge

#541 [BUG] update sosnet urls
  kornia/feature/sosnet.py
  test/feature/test_sosnet.py
Labels: PR: Good to Merge

#533 [TEST][DO NOT MERGE] update to pytorch v1.5.0
  conftest.py
  kornia/feature/laf.py
  kornia/feature/orientation.py
  packaging/README.rst
  packaging/build_wheel.sh
  requirements.txt
  setup.py
  test/color/test_gray.py
  test/common.py
  test/geometry/test_conversions.py
  test/geometry/test_spatial_softargmax.py
Labels: PR: Good to Merge, work in progress

#545 [Enhancement] Local feature fixes and nms improvements
  kornia/feature/laf.py
  kornia/feature/nms.py
  test/feature/test_nms.py
Labels: PR: Good to Merge
