Repository kornia/kornia, pull requests merged in 2020-12, with the labels that each got.

#805 [Feat] improve kornia.enhance docs and coverage
  kornia/color/hls.py
  kornia/enhance/adjust.py
  kornia/enhance/core.py
  kornia/enhance/histogram.py
  kornia/enhance/normalize.py
  test/enhance/test_adjust.py
Labels: enhancement

#706 Augmentation tests refactor
  kornia/testing/__init__.py
  test/augmentation/test_augmentation.py
Labels: work in progress

#810 [Fix] RandomRotation3D cuda fix
  test/augmentation/test_augmentation_3d.py
Labels: bug

#813 [Bug] Fix dtype in ehance LUT
  kornia/enhance/adjust.py
Labels: bug

#816 [Feature] Mask correspondences in motion_from_essential_choose_solution
  kornia/geometry/epipolar/essential.py
  test/geometry/epipolar/test_essential.py
Labels: PR: Good to Merge, enhancement

#807 [Enhancement] TPU tests for for pytorch 1.7, nightly
  .circleci/config.yml
  docker/tpu-tests/tpu_test_cases.jsonnet
Labels: enhancement

#784 [Feat] Add Lab color space
  kornia/__init__.py
  kornia/color/__init__.py
  kornia/color/lab.py
  test/color/test_lab.py
Labels: PR: Good to Merge

#820 [Enhance] Added dtype flag to geometry module
  kornia/augmentation/__init__.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/conversions.py
  kornia/geometry/homography.py
  kornia/geometry/linalg.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/warp/depth_warper.py
  kornia/geometry/warp/homography_warper.py
  kornia/testing/__init__.py
  test/augmentation/test_augmentation.py
  test/geometry/epipolar/test_fundamental.py
  test/geometry/epipolar/test_projection.py
  test/geometry/subpix/test_spatial_softargmax.py
  test/geometry/test_conversions.py
  test/geometry/test_depth.py
  test/geometry/test_homography.py
  test/geometry/test_linalg.py
  test/geometry/test_perspective.py
  test/geometry/test_pinhole.py
  test/geometry/transform/test_affine.py
  test/geometry/transform/test_flip.py
  test/geometry/transform/test_imgwarp.py
  test/geometry/transform/test_projwarp.py
  test/geometry/transform/test_pyramid.py
  test/geometry/warp/test_depth_warper.py
  test/geometry/warp/test_homography_warper.py
Labels: PR: Good to Merge
