Repository kornia/kornia, pull requests merged in 2020-01, with the labels that each got.

#393 Focal loss flat
  kornia/losses/focal.py
  kornia/utils/one_hot.py
  test/test_losses.py
Labels: PR: Good to Merge

#389 add optional mask parameter in scale space
  kornia/feature/scale_space_detector.py
  test/feature/test_scale_space_detector.py
Labels: PR: Good to Merge

#381 transform boxes
  docs/source/geometry.linalg.rst
  kornia/geometry/linalg.py
  test/geometry/test_linalg.py
Labels: PR: Good to Merge

#395 Add ceil_mode to maxblur pool to be able to be used in resnets
  kornia/contrib/max_blur_pool.py
  kornia/filters/filter.py
Labels: PR: Good to Merge

#394 implement resize
  docs/source/geometry.transform.rst
  kornia/geometry/transform/affwarp.py
  test/geometry/transform/test_affine.py
Labels: PR: Needs Review, medium priority

#399 move hsv conversion outside of adjust_saturation and adjust_hue
  kornia/color/__init__.py
  kornia/color/adjust.py
Labels: PR: Good to Merge

#401 Feat/rgba
  kornia/__init__.py
  kornia/color/__init__.py
  kornia/color/rgb.py
  kornia/feature/nms.py
  kornia/geometry/conversions.py
  kornia/geometry/linalg.py
  test/color/test_rgb.py
  test/feature/test_nms.py
  test/filters/test_sobel.py
  test/geometry/test_spatial_softargmax.py
Labels: PR: Needs Review, high priority

#403 implement perspective, random_perspective
  kornia/__init__.py
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
  kornia/augmentation/param_gen.py
  test/augmentation/test_perspective.py
Labels: PR: Good to Merge, high priority

#402 Feat/update pytorch
  kornia/feature/scale_space_detector.py
  kornia/geometry/depth.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/warp/depth_warper.py
  kornia/geometry/warp/homography_warper.py
  requirements.txt
Labels: PR: Good to Merge, high priority

#398 small change in docs
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
Labels: PR: Good to Merge, high priority

#409 Feat/center crop
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
  kornia/geometry/transform/crop.py
  test/augmentation/test_augmentation.py
Labels: PR: Needs Review, high priority

#419 fix augmentation gpu tests
  kornia/augmentation/functional.py
  test/augmentation/test_augmentation.py
Labels: PR: Needs Review, high priority
