Repository kornia/kornia, pull requests merged in 2020-03, with the labels that each got.

#475 [BUG] fix HSV/RGB conversion to device
  kornia/color/hls.py
  kornia/color/hsv.py
  kornia/geometry/transform/imgwarp.py
Labels: PR: Good to Merge

#261 [JIT] create jit module and implement rgb_to_grayscale
  kornia/__init__.py
  kornia/color/gray.py
  kornia/jit/__init__.py
  test/color/test_gray.py
Labels: PR: Good to Merge

#479 [DOCS] fix color_adjust.py tutorial adding plt.show()
  examples/color_adjust.py
Labels: PR: Needs Review

#474 Speed-up warp_affine and fix bugs in RandomAffine [WIP: to add tests]
  Makefile
  docs/source/geometry.conversions.rst
  kornia/augmentation/functional.py
  kornia/augmentation/param_gen.py
  kornia/geometry/conversions.py
  kornia/geometry/transform/crop.py
  kornia/geometry/transform/imgwarp.py
  test/augmentation/test_perspective.py
  test/geometry/test_conversions.py
  test/geometry/transform/test_imgwarp.py
  test/performance/test_imgwarp_speed.py
Labels: PR: Good to Merge, bug
