Repository kornia/kornia, pull requests merged in 2020-08, with the labels that each got.

#604 [DOCS] clean docs warnings
  docs/source/augmentation.rst
  docs/source/geometry.epipolar.rst
  docs/source/geometry.rst
  docs/source/geometry.transform.rst
  docs/source/geometry.warp.rst
  kornia/augmentation/__init__.py
  kornia/feature/matching.py
  kornia/feature/siftdesc.py
  kornia/feature/sosnet.py
  kornia/geometry/camera/perspective.py
  kornia/geometry/homography.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/geometry/warp/homography_warper.py
  kornia/losses/psnr.py
  kornia/losses/total_variation.py
  kornia/utils/image.py
Labels: docs, enhancement

#606 [BUG] updates sosnet git paths
  kornia/feature/sosnet.py
Labels: PR: Good to Merge, bug

#603 [Feat] implement RandomRotation3D and RandomAffine3D
  docs/source/augmentation.rst
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional3d.py
  kornia/augmentation/random_generator3d.py
  kornia/augmentation/utils.py
  kornia/geometry/conversions.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/geometry/warp/homography_warper.py
  test/augmentation/test_augmentation_3d.py
  test/geometry/test_projwarp.py
Labels: enhancement, high priority

#616 [DOCS] Augmentation type
  docs/source/augmentation.rst
Labels: PR: Good to Merge

#618 [Docs] add get_affine_matrix23d, get_affine_matrix3d to docs and update
  docs/source/geometry.transform.rst
  kornia/geometry/transform/imgwarp.py
Labels: PR: Needs Review

#621 fix error in normal_transform_pixel3d
  docs/source/geometry.warp.rst
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/random_generator3d.py
  kornia/geometry/warp/homography_warper.py
  test/augmentation/test_augmentation_3d.py
  test/geometry/warp/test_homography_warper.py
Labels: PR: Good to Merge, bug

#624 added tensor device conversion for solarize params
  kornia/enhance/adjust.py
Labels: PR: Good to Merge

#628 [Feat] Enable variable side resizing in kornia.resize
  kornia/geometry/transform/affwarp.py
  test/geometry/transform/test_affine.py
Labels: PR: Good to Merge

#633 A bunch of small fixes
  docs/source/geometry.transform.rst
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional.py
  kornia/augmentation/random_generator.py
  kornia/augmentation/random_generator3d.py
  kornia/augmentation/utils.py
  kornia/augmentation/utils/__init__.py
  kornia/augmentation/utils/helpers.py
  kornia/augmentation/utils/param_validation.py
  kornia/filters/kernels.py
  kornia/filters/motion.py
  kornia/geometry/transform/imgwarp.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_random_generator.py
Labels: PR: Good to Merge

#640 padding_mode for RandomAffine augmentation
  kornia/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional.py
  kornia/augmentation/random_generator.py
  kornia/constants.py
Labels: PR: Good to Merge

#630 [Feat] Add Affine transformation
  docs/source/geometry.transform.rst
  kornia/geometry/transform/affwarp.py
  test/geometry/transform/test_affine.py
Labels: PR: Good to Merge

#626 [Feat] replace convolution with unfold in contrib.extract_tensor_patches
  kornia/contrib/extract_patches.py
Labels: PR: Good to Merge

#631 [Feat] Add rescale functional and transformation
  docs/source/geometry.transform.rst
  kornia/geometry/transform/affwarp.py
  test/geometry/transform/test_affine.py
Labels: feature request

#645 [Bug] Fix/pipelining multiple augmentations return wrong transformation matrix
  kornia/augmentation/augmentation.py
  test/augmentation/test_augmentation.py
Labels: PR: Good to Merge, bug

#648 [Bug] Fix/flipping returns wrong transformation matrices
  kornia/augmentation/functional.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_transformation_matrix.py
Labels: PR: Good to Merge

#646 [Feat] Affine scale with non-isotropic values
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/random_generator.py
  kornia/augmentation/random_generator3d.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/losses/dice.py
  kornia/losses/focal.py
  kornia/losses/tversky.py
  kornia/utils/grid.py
  test/geometry/test_projwarp.py
  test/geometry/transform/test_affine.py
  test/geometry/transform/test_imgwarp.py
Labels: enhancement
