Repository kornia/kornia, pull requests merged in 2020-11, with the labels that each got.

#759 [Feat] refactor tests for kornia.color
  .github/workflows/docs.yml
  .github/workflows/format.yml
  Makefile
  docs/source/conf.py
  kornia/color/gray.py
  kornia/color/hls.py
  kornia/color/hsv.py
  kornia/color/luv.py
  kornia/color/rgb.py
  kornia/color/xyz.py
  kornia/color/ycbcr.py
  kornia/color/yuv.py
  kornia/jit/__init__.py
  kornia/testing/__init__.py
  pytest.ini
  test/color/test_gray.py
  test/color/test_hls.py
  test/color/test_hsv.py
  test/color/test_luv.py
  test/color/test_rgb.py
  test/color/test_xyz.py
  test/color/test_ycbcr.py
  test/color/test_yuv.py
  test/enhance/test_normalize.py
Labels: enhancement

#764 [Feat] enable doctest in the CI
  .github/workflows/format.yml
Labels: enhancement

#760 Fixed device bug in Sharpen
  kornia/enhance/adjust.py
Labels: bug

#766 [Fix] fixes windows issues with augmentation smoke tests
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_motionblur.py
Labels: bug

#757 Added random param gen tests. Added device awareness for parameter generators.
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/random_generator/random_generator3d.py
  kornia/augmentation/utils/__init__.py
  kornia/augmentation/utils/helpers.py
  kornia/augmentation/utils/param_validation.py
  kornia/filters/kernels.py
  kornia/geometry/transform/crop/crop2d.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_augmentation_mix.py
  test/augmentation/test_perspective.py
  test/augmentation/test_random_generator.py
  test/augmentation/test_random_generator_3d.py
Labels: enhancement

#767 [Fix] Fixes few jit and cuda errors in kornia.color
  kornia/color/gray.py
  kornia/color/hsv.py
  kornia/color/luv.py
  kornia/color/yuv.py
  test/color/test_luv.py
Labels: bug

#789 [Fix] Update setup-miniconda to v2
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/tests_cpu.yml
  .github/workflows/tests_cpu_versions.yml
  .github/workflows/tests_cuda.yml
Labels: bug

#783 Make sharpness output channel nums as input
  kornia/augmentation/augmentation.py
  kornia/enhance/adjust.py
  test/enhance/test_adjust.py
Labels: enhancement

#770 Exposed rng generation device and dtype for augmentations.
  Makefile
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/base.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/random_generator/random_generator3d.py
  kornia/augmentation/utils/helpers.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/utils/helpers.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_augmentation_mix.py
  test/augmentation/test_perspective.py
  test/augmentation/test_random_generator.py
  test/augmentation/test_random_generator_3d.py
  test/geometry/epipolar/test_triangulation.py
Labels: bug, docs

#793 [Fix] Fixed random_crop_size_generator across different devices
  kornia/augmentation/random_generator/random_generator.py
  test/augmentation/test_random_generator.py
Labels: bug

#641 [Feat] Enabled doctest for CI
  .circleci/config.yml.old
  kornia/contrib/extract_patches.py
  kornia/contrib/max_blur_pool.py
  kornia/enhance/zca.py
  kornia/feature/hardnet.py
  kornia/feature/laf.py
  kornia/feature/responses.py
  kornia/feature/siftdesc.py
  kornia/feature/sosnet.py
  kornia/filters/blur.py
  kornia/filters/filter.py
  kornia/filters/gaussian.py
  kornia/filters/kernels.py
  kornia/filters/laplacian.py
  kornia/filters/median.py
  kornia/filters/motion.py
  kornia/filters/sobel.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/conversions.py
  kornia/geometry/linalg.py
  kornia/geometry/subpix/dsnt.py
  kornia/geometry/subpix/spatial_soft_argmax.py
  kornia/geometry/transform/__init__.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/geometry/transform/crop/crop3d.py
  kornia/geometry/transform/flips.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/pyramid.py
  kornia/geometry/warp/depth_warper.py
  kornia/geometry/warp/homography_warper.py
  kornia/losses/depth_smooth.py
  kornia/losses/dice.py
  kornia/losses/focal.py
  kornia/losses/psnr.py
  kornia/losses/ssim.py
  kornia/losses/total_variation.py
  kornia/losses/tversky.py
  kornia/utils/one_hot.py
Labels: enhancement

#800 [Fix] Fixes circleci ref name merge
  .circleci/config.yml
Labels: bug

#796 [Feat] Enabled Torch1.5.1 cpu support
  .github/workflows/tests_cpu_versions.yml
  kornia/augmentation/augmentation.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/utils/helpers.py
  kornia/augmentation/utils/param_validation.py
  kornia/color/hls.py
  kornia/color/hsv.py
  kornia/enhance/adjust.py
  setup.py
  test/enhance/test_adjust.py
Labels: enhancement

#782 [Fix] MotionBlur bug fix and doctest update
  Makefile
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/filters/kernels.py
  kornia/filters/motion.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/utils/helpers.py
  test/augmentation/test_motionblur.py
  test/utils/test_helpers.py
Labels: bug
