Repository kornia/kornia, pull requests merged in 2020-10, with the labels that each got.

#693 Applies #690 - find_homography_dlt performance improvement and weight…
  kornia/geometry/homography.py
  test/geometry/test_homography.py
Labels: PR: Good to Merge

#696 create stale file
  .github/stale.yml
Labels: PR: Good to Merge

#694 Fix broken link in "inverse_depth_smoothness_loss" docs
  kornia/losses/depth_smooth.py
Labels: PR: Good to Merge

#695 [Fix] Zca inverse transform fix
  kornia/enhance/zca.py
  test/enhance/test_zca.py
Labels: PR: Good to Merge

#689 [Feat] 3D volumetric crop implementation
  docs/source/augmentation.rst
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional/functional3d.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/random_generator/random_generator3d.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/crop/__init__.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/geometry/transform/crop/crop3d.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/geometry/warp/homography_warper.py
  kornia/testing/__init__.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/geometry/epipolar/test_essential.py
  test/geometry/transform/crop/test_crop2d.py
  test/geometry/transform/crop/test_crop3d.py
  test/geometry/transform/test_crop.py
  test/geometry/transform/test_projwarp.py
  test/geometry/warp/test_homography_warper.py
Labels: high priority

#713 [Feat] 3D motion blur with element-wise implementations.
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional/functional.py
  kornia/augmentation/functional/functional3d.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/random_generator/random_generator3d.py
  kornia/augmentation/utils/param_validation.py
  kornia/filters/__init__.py
  kornia/filters/filter.py
  kornia/filters/kernels.py
  kornia/filters/motion.py
  kornia/geometry/transform/affwarp.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_motionblur.py
  test/filters/test_motion.py
Labels: high priority

#727 [Fix] gpu tests for crop3d and flip
  docs/source/geometry.transform.rst
  kornia/geometry/transform/crop/crop3d.py
  kornia/geometry/transform/flips.py
  kornia/geometry/transform/projwarp.py
  setup.py
  test/augmentation/test_augmentation_3d.py
  test/geometry/transform/crop/test_crop3d.py
  test/geometry/transform/test_projwarp.py
Labels: PR: Good to Merge, high priority

#728 [Fix] Support non-contiguous input for divergence losses
  kornia/losses/divergence.py
  test/test_losses.py
Labels: PR: Good to Merge

#726 create CHANGELOG and update for 0.4.1
  CHANGELOG.md
Labels: high priority

#736 [Feat] Adds discrete gaussian from project-monai
  docs/source/filters.rst
  kornia/__init__.py
  kornia/filters/__init__.py
  kornia/filters/kernels.py
  test/filters/test_gaussian.py
Labels: PR: Good to Merge

#740 [Fix] Fixed docs for some functions
  kornia/geometry/warp/depth_warper.py
  kornia/geometry/warp/homography_warper.py
Labels: PR: Good to Merge

#744 [Feat] Add Github Actions as main CI
  .circleci/config.yml.old
  .github/workflows/docs.yml
  .github/workflows/format.yml
  .github/workflows/python_package.yml
  .github/workflows/tests_cpu.yml
  .github/workflows/tests_cpu_versions.yml
  .github/workflows/tests_cuda.yml
  docs/requirements.txt
  path.bash.inc
  requirements-dev.txt
  test/geometry/epipolar/test_essential.py
  test/geometry/epipolar/test_fundamental.py
  test/performance/test_project_points_speed.py
Labels: PR: Good to Merge, enhancement, high priority

#754 [Fix] fix gh action versions issue with os matrix
  .github/workflows/tests_cpu_versions.yml
Labels: bug

#755 [Fix] pytorch version to 1.6.0 in cuda tests
  .github/workflows/tests_cuda.yml
Labels: bug

#733 Added sample augmentation readme
  kornia/augmentation/README.md
Labels: docs

#756 refactor setup_dev_env script
  Makefile
  requirements.txt
  setup_dev_env.sh
Labels: enhancement
