Repository kornia/kornia, pull requests merged in 2020-07, with the labels that each got.

#591 Dog and fix features
  docs/source/feature.rst
  kornia/feature/__init__.py
  kornia/feature/laf.py
  kornia/feature/nms.py
  kornia/feature/responses.py
  kornia/feature/scale_space_detector.py
  kornia/filters/kernels.py
  kornia/geometry/spatial_soft_argmax.py
  kornia/geometry/transform/pyramid.py
  test/feature/test_scale_space_detector.py
  test/geometry/test_spatial_softargmax.py
  test/geometry/transform/test_crop.py
  test/geometry/transform/test_pyramid.py
Labels: bug

#575 implement filter3D
  docs/source/filters.rst
  kornia/__init__.py
  kornia/filters/__init__.py
  kornia/filters/filter.py
  test/filters/test_filters.py
Labels: high priority

#579 [Docs] fix Tversky equation
  kornia/losses/tversky.py
Labels: PR: Good to Merge

#598 Now SIFTdesc throws an exception when the input parameters are incompatible
  kornia/feature/siftdesc.py
Labels: PR: Good to Merge, high priority

#587 Feat/warp projective
  docs/source/geometry.transform.rst
  kornia/filters/filter.py
  kornia/geometry/transform/__init__.py
  kornia/geometry/transform/projwarp.py
  test/geometry/test_projwarp.py
Labels: PR: Good to Merge, enhancement, high priority

#597 [BUG] made kornia versions explicit to pytorch version
  setup.py
Labels: PR: Good to Merge, high priority

#552 [WIP] Feature matching and H/F/E estimation for SFM
  docs/source/feature.rst
  docs/source/geometry.rst
  kornia/feature/__init__.py
  kornia/feature/matching.py
  kornia/geometry/__init__.py
  kornia/geometry/homography.py
  test/feature/test_matching.py
  test/geometry/test_homography.py
Labels: PR: Good to Merge, high priority

#592 Init 3D augmentations
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional.py
  kornia/augmentation/functional3d.py
  kornia/augmentation/random_generator.py
  kornia/augmentation/types.py
  kornia/augmentation/utils.py
Labels: high priority
