Repository kornia/kornia, pull requests merged in 2021-01, with the labels that each got.

#826 [Enhance] Added better augmentation support for backpropagation
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/functional/functional.py
  kornia/augmentation/functional/functional3d.py
  kornia/augmentation/mix_augmentation.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/augmentation/random_generator/random_generator3d.py
  kornia/augmentation/utils/helpers.py
  kornia/augmentation/utils/param_validation.py
  kornia/filters/kernels.py
  kornia/filters/motion.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/utils/helpers.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_mix.py
  test/augmentation/test_backward.py
  test/augmentation/test_backward_3d.py
  test/augmentation/test_random_generator.py
  test/augmentation/test_random_generator_3d.py
Labels: enhancement

#773 add GaussianBlur augmentation
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  test/augmentation/test_augmentation.py
Labels: PR: Good to Merge, high priority

#831 morphology
  docs/.gitignore
  docs/source/index.rst
  docs/source/morphology.rst
  kornia/__init__.py
  kornia/morphology/__init__.py
  kornia/morphology/basic_operators.py
  kornia/morphology/morphology.py
  kornia/morphology/open_close.py
  test/morphology/test_black_hat.py
  test/morphology/test_close.py
  test/morphology/test_dilation.py
  test/morphology/test_erosion.py
  test/morphology/test_gradient.py
  test/morphology/test_open.py
  test/morphology/test_top_hat.py
Labels: high priority

#834 [Feat] Add tpu support for the losses module
  docker/tpu-tests/tpu_test_cases.jsonnet
  docs/source/references.bib
  kornia/losses/depth_smooth.py
  kornia/losses/dice.py
  kornia/losses/divergence.py
  kornia/losses/focal.py
  kornia/losses/tversky.py
  kornia/utils/one_hot.py
  test/test_losses.py
Labels: feature request, high priority

#841 MKD rebased
  docs/source/feature.rst
  docs/source/geometry.conversions.rst
  docs/source/references.bib
  kornia/__init__.py
  kornia/feature/__init__.py
  kornia/feature/mkd.py
  kornia/geometry/conversions.py
  test/feature/test_mkd.py
  test/geometry/test_conversions.py
Labels: PR: Good to Merge, high priority

#842 [Fix] Fixes docs in morphology and morphology
  kornia/augmentation/augmentation.py
  kornia/feature/mkd.py
  kornia/morphology/basic_operators.py
  kornia/morphology/morphology.py
  kornia/morphology/open_close.py
  test/feature/test_mkd.py
Labels: docs

#845 [Add] Updates CI with pytorch 1.7.1
  .github/workflows/tests_cpu.yml
  .github/workflows/tests_cpu_versions.yml
  .github/workflows/tests_cuda.yml
  .github/workflows/tests_cuda_versions.yml
Labels: enhancement, high priority

#846 Added TFeat, AffNet, OriNet to kornia.features
  docs/source/feature.rst
  docs/source/references.bib
  kornia/feature/__init__.py
  kornia/feature/affine_shape.py
  kornia/feature/orientation.py
  kornia/feature/tfeat.py
  test/feature/test_affine_shape_estimator.py
  test/feature/test_local_features_orientation.py
  test/feature/test_tfeat.py
Labels: enhancement, high priority

#848 [WIP] Features jit
  kornia/feature/affine_shape.py
  kornia/feature/laf.py
  kornia/feature/mkd.py
  kornia/feature/orientation.py
  kornia/feature/responses.py
  kornia/feature/siftdesc.py
  kornia/feature/sosnet.py
  test/feature/test_affine_shape_estimator.py
  test/feature/test_hardnet.py
  test/feature/test_laf.py
  test/feature/test_local_features_orientation.py
  test/feature/test_mkd.py
  test/feature/test_responces_local_features.py
  test/feature/test_siftdesc.py
  test/feature/test_sosnet.py
Labels: enhancement, high priority

#847 [Fix] Refactor psnr and ssim losses
  docs/source/losses.rst
  kornia/losses/__init__.py
  kornia/losses/divergence.py
  kornia/losses/focal.py
  kornia/losses/psnr.py
  kornia/losses/ssim.py
  kornia/losses/total_variation.py
  test/test_losses.py
Labels: enhancement, high priority

#817 [Feat] Added VideoSequential for video augmentations
  docs/source/augmentation.rst
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/container/__init__.py
  kornia/augmentation/container/video.py
  kornia/enhance/normalize.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_backward.py
  test/augmentation/test_backward_3d.py
  test/augmentation/test_container.py
  test/enhance/test_normalize.py
Labels: PR: Good to Merge, enhancement, high priority

#850 [Fix] Fixes ssim_loss average
  kornia/losses/ssim.py
Labels: bug, high priority

#855 [Fix] Mark to skip gradcheck test in tfeat
  test/feature/test_tfeat.py
Labels: bug, high priority

#854 [Fix] Drop support for PyTorch 1.5.1
  .github/workflows/tests_cpu_versions.yml
  .github/workflows/tests_cuda_versions.yml
  README.rst
Labels: feature request, high priority

#853 [Feat] Add elastic transform 2d
  docs/source/augmentation.rst
  docs/source/geometry.transform.rst
  docs/source/references.bib
  kornia/augmentation/augmentation.py
  kornia/augmentation/functional/functional3d.py
  kornia/feature/affine_shape.py
  kornia/feature/orientation.py
  kornia/filters/kernels.py
  kornia/geometry/transform/__init__.py
  kornia/geometry/transform/elastic_transform.py
  test/feature/test_mkd.py
  test/geometry/transform/test_elastic_transform.py
Labels: enhancement, high priority

#858 [Fix] Fixes jit tests in feature for pytorch 1.6
  .github/workflows/tests_cpu.yml
  kornia/feature/affine_shape.py
  kornia/feature/hardnet.py
  kornia/feature/mkd.py
  kornia/feature/orientation.py
  kornia/feature/sosnet.py
Labels: bug, enhancement

#857 Added docs for VideoSequential
  docs/source/augmentation.base.rst
  docs/source/augmentation.container.rst
  docs/source/augmentation.module.rst
  docs/source/augmentation.rst
Labels: docs

#861 [Enhance] pytorch nightly fixes
  kornia/augmentation/mix_augmentation.py
  kornia/augmentation/utils/helpers.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_augmentation_mix.py
  test/geometry/subpix/test_spatial_softargmax.py
  test/geometry/test_linalg.py
  test/geometry/transform/test_affine.py
  test/geometry/transform/test_imgwarp.py
  test/geometry/transform/test_projwarp.py
  test/geometry/warp/test_depth_warper.py
  test/geometry/warp/test_homography_warper.py
Labels: enhancement

#864 fix comment in angle_axis_to_rotation_matrix
  kornia/geometry/conversions.py
Labels: PR: Good to Merge, docs

#871 Add epsilon value to rgb_to_hsv
  kornia/color/hsv.py
Labels: bug
