Repository kornia/kornia, pull requests merged in 2021-09, with the labels that each got.

#1241 Fix docstrings, enhance docs and change an assertion
  docs/source/geometry.camera.pinhole.rst
  docs/source/geometry.epipolar.rst
  kornia/geometry/epipolar/numeric.py
  kornia/geometry/epipolar/projection.py
Labels: enhancement, docs, kornia::geometry

#1242 Add docformatter in pre-commit
  .pre-commit-config.yaml
  conftest.py
  examples/depth_regression/main.py
  examples/depth_warper/main.py
  examples/homography_regression/main.py
  kornia/augmentation/base.py
  kornia/augmentation/container/augment.py
  kornia/augmentation/utils/param_validation.py
  kornia/enhance/histogram.py
  kornia/feature/affine_shape.py
  kornia/feature/defmo.py
  kornia/feature/hardnet.py
  kornia/feature/laf.py
  kornia/feature/nms.py
  kornia/feature/orientation.py
  kornia/filters/kernels.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/depth.py
  kornia/geometry/epipolar/numeric.py
  kornia/geometry/epipolar/projection.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/geometry/transform/crop/crop3d.py
  kornia/testing/__init__.py
  kornia/utils/grid.py
  kornia/utils/helpers.py
  kornia/utils/image.py
  test/enhance/test_zca.py
  test/geometry/test_conversions.py
  test/integration/test_conversions.py
  test/integration/test_soft_argmax2d.py
Labels: docs, high priority, code heatlh

#1243 Add bandit B110 test and fix
  .github/workflows/tests_cuda.yml
  .pre-commit-config.yaml
  kornia/feature/hardnet.py
  setup.py
Labels: high priority, code heatlh

#1246 Add yesqa in the pre-commit
  .pre-commit-config.yaml
  docs/source/conf.py
  kornia/__init__.py
  kornia/feature/affine_shape.py
  kornia/feature/hardnet.py
  kornia/feature/orientation.py
  kornia/feature/siftdesc.py
  kornia/feature/tfeat.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/conversions.py
  kornia/geometry/transform/imgwarp.py
  kornia/utils/metrics/confusion_matrix.py
  test/augmentation/test_augmentation.py
  test/feature/test_mkd.py
Labels: high priority, code heatlh

#1248 Add bandit B101 test and fix
  .pre-commit-config.yaml
  kornia/augmentation/container/patch.py
Labels: code heatlh

#1250 Fix unused variable found
  examples/depth_warper/main.py
  examples/homography_regression/main.py
  kornia/augmentation/augmentation.py
  kornia/color/rgb.py
  kornia/enhance/equalization.py
  kornia/enhance/histogram.py
  kornia/enhance/zca.py
  kornia/feature/affine_shape.py
  kornia/feature/laf.py
  kornia/feature/scale_space_detector.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/depth.py
  kornia/geometry/epipolar/projection.py
  kornia/geometry/epipolar/triangulation.py
  kornia/geometry/homography.py
  kornia/geometry/subpix/spatial_soft_argmax.py
  kornia/geometry/transform/elastic_transform.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/geometry/transform/pyramid.py
  kornia/geometry/warp/depth_warper.py
  kornia/geometry/warp/homography_warper.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_mix.py
  test/augmentation/test_backward.py
  test/augmentation/test_base.py
  test/augmentation/test_container.py
  test/augmentation/test_random_generator.py
  test/enhance/test_adjust.py
  test/enhance/test_histogram.py
  test/feature/test_nms.py
  test/filters/test_blur.py
  test/filters/test_blur_pool.py
  test/filters/test_canny.py
  test/filters/test_filters.py
  test/filters/test_median.py
  test/filters/test_motion.py
  test/geometry/calibration/test_undistort.py
  test/geometry/epipolar/test_essential.py
  test/geometry/epipolar/test_fundamental.py
  test/geometry/test_conversions.py
  test/geometry/test_linalg.py
  test/geometry/transform/test_affine.py
  test/geometry/transform/test_homography_warper.py
  test/geometry/transform/test_imgwarp.py
  test/geometry/transform/test_projwarp.py
  test/geometry/transform/test_pyramid.py
  test/geometry/transform/test_thin_plate_spline.py
  test/integration/test_focal.py
  test/integration/test_soft_argmax2d.py
  test/integration/test_warp.py
  test/performance/test_imgwarp_speed.py
  test/performance/test_project_points_speed.py
  test/test_losses.py
  test/utils/test_grid.py
  test/utils/test_helpers.py
Labels: code heatlh

#1251 Enable bandit tests B311
  .pre-commit-config.yaml
Labels: high priority, code heatlh

#1252 Fix unused variable found 2/n
  examples/depth_regression/main.py
  kornia/augmentation/augmentation.py
  kornia/feature/laf.py
  kornia/feature/orientation.py
  kornia/geometry/depth.py
  kornia/geometry/epipolar/essential.py
  kornia/geometry/transform/pyramid.py
  kornia/geometry/warp/depth_warper.py
  test/augmentation/test_container.py
Labels: high priority, code heatlh

#1247 Create dependabot.yml
  .github/dependabot.yml
Labels: high priority, code heatlh

#1253 Add ImageRegistrator API
  docs/source/_static/img/registration.gif
  docs/source/geometry.rst
  docs/source/geometry.transform.rst
  kornia/geometry/transform/__init__.py
  kornia/geometry/transform/image_registrator.py
  test/geometry/transform/test_image_registrator.py
Labels: enhancement, kornia::geometry

#1266 return all learned modules by default in eval() mode
  kornia/feature/affine_shape.py
  kornia/feature/defmo.py
  kornia/feature/hardnet.py
  kornia/feature/mkd.py
  kornia/feature/orientation.py
  kornia/feature/sosnet.py
  kornia/feature/tfeat.py
Labels: enhancement

#1218 LoFTR inference basic PR [WIP]
  docs/source/feature.rst
  docs/source/references.bib
  kornia/feature/__init__.py
  kornia/feature/loftr/__init__.py
  kornia/feature/loftr/backbone/__init__.py
  kornia/feature/loftr/backbone/resnet_fpn.py
  kornia/feature/loftr/loftr.py
  kornia/feature/loftr/loftr_module/__init__.py
  kornia/feature/loftr/loftr_module/fine_preprocess.py
  kornia/feature/loftr/loftr_module/linear_attention.py
  kornia/feature/loftr/loftr_module/transformer.py
  kornia/feature/loftr/utils/__init__.py
  kornia/feature/loftr/utils/coarse_matching.py
  kornia/feature/loftr/utils/fine_matching.py
  kornia/feature/loftr/utils/geometry.py
  kornia/feature/loftr/utils/position_encoding.py
  kornia/feature/loftr/utils/supervision.py
  test/feature/test_loftr.py
Labels: work in progress, feature request, kornia::feature

#1268 docs revamp with furo!
  docs/requirements.txt
  docs/source/_static/css/copybtn.css
  docs/source/_static/css/pytorch_theme.css
  docs/source/_static/img/kornia_logo_mini.png
  docs/source/applications/image_augmentations.rst
  docs/source/applications/image_matching.rst
  docs/source/applications/image_registration.rst
  docs/source/applications/intro.rst
  docs/source/applications/video_deblur.rst
  docs/source/augmentation.rst
  docs/source/community/bibliography.rst
  docs/source/community/contribute.rst
  docs/source/community/faqs.rst
  docs/source/community/governance.rst
  docs/source/conf.py
  docs/source/get-started/about.rst
  docs/source/get-started/highlights.rst
  docs/source/get-started/installation.rst
  docs/source/get-started/introduction.rst
  docs/source/index.rst
  kornia/geometry/transform/imgwarp.py
Labels: docs

#1269 fix docs logo path
  docs/source/conf.py
Labels: docs

#1231 [Feat] Enable ImageSequential and VideoSequential to AugmentationSequential
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/base.py
  kornia/augmentation/container/image.py
  kornia/augmentation/container/patch.py
  kornia/augmentation/container/utils.py
  kornia/augmentation/container/video.py
  kornia/geometry/linalg.py
  test/augmentation/test_container.py
Labels: enhancement, kornia::augmentations

#1279 Add models section in docs and some improvements
  docs/requirements.txt
  docs/source/_static/img/kornia_logo_only_dark.svg
  docs/source/_static/img/kornia_logo_only_light.svg
  docs/source/applications/image_augmentations.rst
  docs/source/applications/image_registration.rst
  docs/source/applications/intro.rst
  docs/source/conf.py
  docs/source/get-started/highlights.rst
  docs/source/get-started/introduction.rst
  docs/source/index.rst
  docs/source/models/affnet.rst
  docs/source/models/defmo.rst
  docs/source/models/hardnet.rst
  docs/source/models/loftr.rst
Labels: docs

#1254 [feat] Added differentiable Hausdorff Distance (HD) loss
  docs/source/losses.rst
  docs/source/references.bib
  kornia/losses/__init__.py
  kornia/losses/hausdorff.py
  requirements-dev.txt
  test/losses/test_hd.py
  test/losses/test_losses.py
Labels: enhancement, high priority, kornia::losses

#1278 fix test loading before pytorch 1.6
  test/feature/test_loftr.py
Labels: high priority, code heatlh, kornia::feature

#1280 [doc] Refined docs
  docs/source/applications/image_augmentations.rst
  docs/source/applications/image_matching.rst
  docs/source/augmentation.rst
  docs/source/geometry.rst
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/patch.py
  kornia/losses/hausdorff.py
Labels: enhancement, docs

#1287 specify that angles are in radians for conversion functions
  kornia/geometry/conversions.py
Labels: docs, high priority

#1284 fixes torch version parse and add temporal packaging dependency
  kornia/utils/_compat.py
  setup.py
Labels: bug, high priority

#1288 small improvement in the augmentations docs
  docs/source/applications/image_augmentations.rst
Labels: docs, high priority

#1281 [ENHANCE] removed deprecated codes for v6.0
  kornia/__init__.py
  kornia/contrib/__init__.py
  kornia/contrib/max_blur_pool.py
  kornia/geometry/bbox.py
  kornia/geometry/linalg.py
  kornia/geometry/transform/affwarp.py
  kornia/geometry/transform/crop/crop2d.py
  kornia/geometry/transform/crop/crop3d.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  test/augmentation/test_augmentation.py
  test/enhance/test_normalize.py
  test/geometry/test_linalg.py
  test/geometry/transform/test_affine.py
  test/geometry/transform/test_bbox.py
  test/losses/test_hd.py
  test/test_contrib.py
Labels: high priority

#1292 [doc] Updated github button & removed announcement
  docs/source/_static/js/custom.js
  docs/source/community/chinese.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: docs

#1296 add vision transformer (vit)
  docs/source/conf.py
  docs/source/contrib.rst
  docs/source/geometry.linalg.rst
  docs/source/index.rst
  docs/source/models/affnet.rst
  docs/source/models/defmo.rst
  docs/source/models/hardnet.rst
  docs/source/models/loftr.rst
  docs/source/models/vit.rst
  docs/source/references.bib
  kornia/contrib/__init__.py
  kornia/contrib/classification.py
  kornia/contrib/vit.py
  test/test_contrib.py
Labels: enhancement

#1286 Add PadTo to kornia.augmentation
  kornia/augmentation/__init__.py
  kornia/augmentation/augmentation.py
  kornia/augmentation/base.py
  test/augmentation/test_augmentation.py
Labels: feature request, high priority, kornia::augmentations

#1295 fix issue of image_histogram2d
  kornia/enhance/histogram.py
  test/enhance/test_histogram.py
Labels: bug, enhancement

#1301 hotfix for memory issue with vit and mypy error
  kornia/contrib/vit.py
Labels: bug

#1307 Add Training API
  README.md
  docs/source/get-started/installation.rst
  docs/source/get-started/training.rst
  docs/source/index.rst
  docs/source/x.rst
  examples/train/image_classifier/README.rst
  examples/train/image_classifier/config.yaml
  examples/train/image_classifier/main.py
  examples/train/image_classifier/requirements.txt
  kornia/__init__.py
  kornia/x/__init__.py
  kornia/x/callbacks.py
  kornia/x/metrics.py
  kornia/x/trainer.py
  kornia/x/trainer_classification.py
  kornia/x/utils.py
  requirements-dev.txt
  setup.py
  test/test_x.py
Labels: enhancement, kornia::trainer

#1313 Fix binary focal loss
  kornia/losses/focal.py
  test/losses/test_losses.py
Labels: bug, kornia::losses

#1314 reorganize requirements files
  .github/workflows/format.yml
  .github/workflows/tests_cpu.yml
  .github/workflows/tests_cpu_versions.yml
  .github/workflows/tests_cuda.yml
  requirements/dev.txt
  requirements/x.txt
  setup.py
Labels: enhancement

#1316 hotfix to remove logger initialization
  kornia/x/trainer.py
Labels: bug

#1309 [feat] Added combine patches
  kornia/contrib/__init__.py
  kornia/contrib/extract_patches.py
  test/test_contrib.py
Labels: feature request, high priority, kornia::contrib

#1318 fix kornia.geometry.subpix.spatial_soft_argmax imports
  kornia/geometry/subpix/spatial_soft_argmax.py
Labels: bug, code heatlh

#1319 Fixed a simple typo in __init__.py
  docs/source/get-started/training.rst
  kornia/__init__.py
Labels: code heatlh

#1325 create metrics submodule
  docs/source/index.rst
  docs/source/losses.rst
  docs/source/metrics.rst
  docs/source/utils.rst
  kornia/__init__.py
  kornia/geometry/epipolar/__init__.py
  kornia/geometry/epipolar/_metrics.py
  kornia/losses/__init__.py
  kornia/losses/psnr.py
  kornia/losses/ssim.py
  kornia/metrics/__init__.py
  kornia/metrics/accuracy.py
  kornia/metrics/average_meter.py
  kornia/metrics/confusion_matrix.py
  kornia/metrics/mean_iou.py
  kornia/metrics/psnr.py
  kornia/metrics/ssim.py
  kornia/utils/__init__.py
  kornia/utils/metrics/__init__.py
  kornia/x/metrics.py
  kornia/x/trainer.py
  kornia/x/trainer_classification.py
  test/losses/test_losses.py
  test/test_metrics.py
  test/test_x.py
  test/utils/test_metrics.py
Labels: kornia::metrics

#1323 :star2: Add semantic segmentation trainer
  docs/source/get-started/training.rst
  docs/source/metrics.rst
  docs/source/x.rst
  examples/train/image_classifier/main.py
  examples/train/semantic_segmentation/README.rst
  examples/train/semantic_segmentation/config.yaml
  examples/train/semantic_segmentation/main.py
  examples/train/semantic_segmentation/requirements.txt
  kornia/x/__init__.py
  kornia/x/trainer.py
  kornia/x/trainer_classification.py
  kornia/x/utils.py
  test/x/test_image_classification.py
  test/x/test_segmentation.py
  test/x/test_x.py
Labels: feature request, PR: Good to Merge, kornia::trainer

#1331 :boot: Improves `kornia.color` documentation
  docs/generate_example_images.py
  docs/source/color.rst
  kornia/color/rgb.py
  test/color/test_hsv.py
Labels: docs, kornia::color

#1332 :ski: add documentation for image classification and segmentation
  docs/source/_static/css/main.css
  docs/source/applications/image_augmentations.rst
  docs/source/applications/image_classification.rst
  docs/source/applications/semantic_segmentation.rst
  docs/source/conf.py
  docs/source/get-started/training.rst
  docs/source/index.rst
  docs/source/models/vit.rst
  kornia/x/trainer_classification.py
Labels: docs, kornia::trainer

#1330 Fix bug in create_meshgrid3d along depth
  kornia/augmentation/augmentation3d.py
  kornia/utils/grid.py
Labels: bug

#1336 :minidisc: add missing snippets and improvements
  conftest.py
  docs/source/contrib.rst
  docs/source/losses.rst
  kornia/contrib/connected_components.py
  kornia/contrib/extract_patches.py
  kornia/geometry/calibration/undistort.py
  kornia/geometry/camera/perspective.py
  kornia/geometry/conversions.py
  kornia/geometry/depth.py
  kornia/metrics/accuracy.py
  kornia/metrics/confusion_matrix.py
  kornia/metrics/mean_iou.py
  kornia/utils/image.py
Labels: docs
