Repository kornia/kornia, pull requests merged in 2021-08, with the labels that each got.

#1187 Fix wrong source points for RandomThinPlateSpline
  kornia/augmentation/augmentation.py
Labels: bug, kornia::augmentations

#1189 Fix RandomElasticTransform ignores same_on_batch
  docs/source/_extra/googlef1b16a85a18694bd.html
  docs/source/conf.py
  kornia/augmentation/augmentation.py
  test/augmentation/test_augmentation.py
Labels: bug, kornia::augmentations

#1180 docstring indentation fixes
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/image.py
  kornia/augmentation/container/patch.py
  kornia/augmentation/container/video.py
Labels: enhancement, docs

#1178 Fixed bugs in patchsequential. Remove fill_diagonal operation for better ONNX support.
  kornia/augmentation/container/patch.py
  kornia/geometry/transform/imgwarp.py
Labels: bug, kornia::augmentations, kornia::onnx

#1172 [Feature] Differentiable image histogram using kernel density estimation.
  kornia/enhance/histogram.py
  test/enhance/test_histogram.py
Labels: enhancement, high priority, kornia::enhance

#1184 Add the connected components labeling algorithm
  docs/source/contrib.rst
  kornia/contrib/__init__.py
  kornia/contrib/connected_components.py
  test/test_contrib.py
Labels: enhancement, high priority, kornia::contrib

#1190 bump to version 0.5.8
  CHANGELOG.md
  setup.py
Labels: high priority

#1200 link the connected components algorithm to the documentation
  kornia/contrib/connected_components.py
Labels: docs

#1207 Unexpected keyword argument in function call
  test/geometry/transform/test_affine.py
Labels: code heatlh

#1211 Added tests, fixed docstrings and made some other changes
  kornia/geometry/camera/pinhole.py
  test/geometry/test_pinhole.py
Labels: enhancement, high priority, kornia::geometry

#1214 Fix typos discovered by codespell
  .pre-commit-config.yaml
  docs/source/conf.py
  docs/source/installation.rst
  examples/depth_regression/download_data.sh
  examples/depth_regression/readme.rst
  examples/depth_warper/download_data.sh
  examples/depth_warper/readme.rst
  examples/homography_regression/download_data.sh
  examples/homography_regression/main.py
  examples/homography_regression/readme.rst
  kornia/augmentation/augmentation.py
  kornia/augmentation/augmentation3d.py
  kornia/augmentation/base.py
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/patch.py
  kornia/augmentation/container/video.py
  kornia/augmentation/mix_augmentation.py
  kornia/augmentation/random_generator/random_generator.py
  kornia/color/hsv.py
  kornia/contrib/connected_components.py
  kornia/enhance/adjust.py
  kornia/enhance/equalization.py
  kornia/feature/laf.py
  kornia/filters/filter.py
  kornia/filters/kernels.py
  kornia/geometry/calibration/undistort.py
  kornia/geometry/camera/pinhole.py
  kornia/geometry/camera/stereo.py
  kornia/geometry/depth.py
  kornia/geometry/epipolar/essential.py
  kornia/geometry/epipolar/projection.py
  kornia/geometry/linalg.py
  kornia/geometry/transform/elastic_transform.py
  kornia/geometry/transform/homography_warper.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/projwarp.py
  kornia/geometry/transform/thin_plate_spline.py
  kornia/morphology/morphology.py
  kornia/utils/metrics/confusion_matrix.py
  packaging/README.rst
  setup.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_container.py
  test/geometry/calibration/test_undistort.py
  test/geometry/test_bbox.py
  test/geometry/test_depth_warper.py
  test/performance/test_project_points_speed.py
  test/utils/test_helpers.py
Labels: code heatlh

#1210 Do not ignore undefined names in Python code
  .pre-commit-config.yaml
  examples/depth_warper/main.py
  kornia/geometry/camera/pinhole.py
  setup.cfg
  setup.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_random_generator.py
  test/enhance/test_adjust.py
  test/enhance/test_equalization.py
  test/geometry/epipolar/test_fundamental.py
  test/geometry/epipolar/test_triangulation.py
Labels: code heatlh

#1219 add missing image_histogram2d in docs
  docs/source/enhance.rst
Labels: docs, kornia::enhance

#1221 enable pyupgrade as pre-commit
  .pre-commit-config.yaml
  examples/depth_regression/main.py
  kornia/feature/defmo.py
Labels: code heatlh

#1235 Fixes warnings and add compatibility stub in torch solve
  docs/source/_static/css/copybtn.css
  kornia/geometry/subpix/spatial_soft_argmax.py
  kornia/geometry/transform/thin_plate_spline.py
  kornia/utils/_compat.py
  kornia/utils/helpers.py
Labels: code heatlh

#1236 Fix mypy issue with torch.linalg
  kornia/utils/_compat.py
Labels: code heatlh

#1232 bump 0.5.9 release version
  CHANGELOG.md
  setup.py
Labels: high priority

#1240 Function contains unused argument
  kornia/augmentation/utils/helpers.py
  kornia/feature/affine_shape.py
  kornia/filters/unsharp.py
  kornia/geometry/subpix/spatial_soft_argmax.py
  kornia/utils/draw.py
Labels: code heatlh
