Repository kornia/kornia, pull requests merged in 2022-12, with the labels that each got.

#2047 Update constants to be able to inherit types from `get` method
  kornia/constants.py
Labels: code heatlh :pill:

#2046 Pass along data_keys or extra_args in *ApplyInverse with containers
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/utils.py
  test/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2086 enable `check_untyped_defs` on mypy
  kornia/__tmp__.py
  kornia/feature/adalam/ransac.py
  kornia/feature/adalam/utils.py
  kornia/feature/loftr/utils/position_encoding.py
  kornia/feature/siftdesc.py
  kornia/feature/sold2/backbones.py
  kornia/filters/dexined.py
  kornia/metrics/average_meter.py
  kornia/nerf/data_utils.py
  kornia/testing/__init__.py
  kornia/utils/helpers.py
  setup.cfg
Labels: code heatlh :pill:

#2092 enable `disallow_any_generics` on mypy
  kornia/augmentation/base.py
  kornia/augmentation/container/base.py
  kornia/augmentation/container/image.py
  kornia/augmentation/container/utils.py
  kornia/augmentation/utils/helpers.py
  kornia/augmentation/utils/param_validation.py
  kornia/contrib/diamond_square.py
  kornia/contrib/face_detection.py
  kornia/contrib/image_stitching.py
  kornia/contrib/lambda_module.py
  kornia/feature/adalam/adalam.py
  kornia/feature/adalam/core.py
  kornia/feature/affine_shape.py
  kornia/feature/hardnet.py
  kornia/feature/hynet.py
  kornia/feature/integrated.py
  kornia/feature/keynet.py
  kornia/feature/loftr/loftr.py
  kornia/feature/matching.py
  kornia/feature/mkd.py
  kornia/feature/orientation.py
  kornia/feature/siftdesc.py
  kornia/feature/sold2/backbones.py
  kornia/feature/sold2/sold2.py
  kornia/feature/sold2/sold2_detector.py
  kornia/feature/sosnet.py
  kornia/feature/tfeat.py
  kornia/geometry/transform/crop2d.py
  kornia/geometry/transform/image_registrator.py
  kornia/geometry/transform/pyramid.py
  kornia/grad_estimator/ste.py
  kornia/losses/hausdorff.py
  kornia/metrics/mean_average_precision.py
  kornia/nerf/data_utils.py
  kornia/testing/__init__.py
  kornia/utils/image.py
  kornia/x/callbacks.py
  kornia/x/trainer.py
  kornia/x/trainers.py
  kornia/x/utils.py
  setup.cfg
Labels: code heatlh :pill:

#1987 Add `TensorWrapper`, `Vector3`, `Scalar` and improvements in `fit_plane`
  examples/geometry/fit_plane3.py
  kornia/core/_backend.py
  kornia/core/tensor_wrapper.py
  kornia/geometry/linalg.py
  kornia/geometry/line.py
  kornia/geometry/plane.py
  kornia/geometry/vector.py
  kornia/losses/total_variation.py
  kornia/testing/__init__.py
  kornia/utils/grid.py
  kornia/utils/helpers.py
  setup_dev_env.sh
  test/core/test_tensor_wrapper.py
  test/geometry/test_plane.py
  test/geometry/test_vector.py
Labels: enhancement :rocket:, module: geometry

#2088 fix parameters generator to be reproducible (3D)
  kornia/augmentation/utils/param_validation.py
  test/augmentation/test_random_generator_3d.py
Labels: module: augmentations

#2107 update config tests
  conftest.py
  setup.cfg
Labels: code heatlh :pill:

#2114 Fix AugmentationSequential to return list of boxes
  kornia/augmentation/container/augment.py
  kornia/testing/__init__.py
  test/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2100 Bump pytorch version
  .github/workflows/pr_test_cpu.yml
  .github/workflows/pr_test_typing.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_typing.yml
Labels: CI :gear:

#2122 add `PadTo` to docs
  docs/generate_example_images.py
  docs/source/augmentation.module.rst
  kornia/augmentation/_2d/geometric/pad.py
Labels: docs :books:, module: augmentations
