Repository kornia/kornia, pull requests merged in 2022-01, with the labels that each got.

#1521 Fix #1520
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/utils.py
  kornia/geometry/boxes.py
  test/augmentation/test_container.py
Labels: PR: Good to Merge :ok_hand:

#1518 update to pytorch 1.10.1
  .github/workflows/tests_cpu.yml
  kornia/enhance/histogram.py
  setup_dev_env.sh
  test/enhance/test_histogram.py
Labels: PR: Good to Merge :ok_hand:, P1 🚨, code heatlh :pill:

#1506 allow to pass a new K to distort and undistort points as in opencv
  kornia/geometry/calibration/distort.py
  kornia/geometry/calibration/undistort.py
  test/geometry/calibration/test_distort.py
  test/geometry/calibration/test_undistort.py
Labels: enhancement :rocket:, PR: Good to Merge :ok_hand:, P1 🚨, module: geometry

#1519 Added Hanning kernel, prepare for KCF tracking
  docs/source/filters.rst
  kornia/filters/__init__.py
  kornia/filters/kernels.py
  test/filters/test_hanning.py
Labels: feature request, PR: Good to Merge :ok_hand:, P1 🚨, module: filters

#1530 fix cross_product_matrix batch dimensionality
  kornia/geometry/epipolar/numeric.py
  test/geometry/epipolar/test_numeric.py
Labels: bug :bug:, module: geometry

#1529 Update README.rst
  examples/train/semantic_segmentation/README.rst
Labels: PR: Good to Merge :ok_hand:, docs :books:

#1490 Add distance transform implementation
  docs/source/contrib.rst
  docs/source/references.bib
  kornia/contrib/__init__.py
  kornia/contrib/distance_transform.py
  test/test_contrib.py
Labels: feature request, P1 🚨, module: contrib

#1535 update object detection trainer
  kornia/x/trainers.py
Labels: bug :bug:, module: trainer

#1536 Fixed #1534 nested augmentation sequential bug
  kornia/augmentation/container/utils.py
  test/augmentation/test_container.py
Labels: enhancement :rocket:, module: augmentations

#1546 Fixes to device in augmentations
  kornia/augmentation/_2d/intensity/posterize.py
  kornia/augmentation/container/utils.py
  kornia/augmentation/random_generator/_2d/posterize.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#1547 Add Resize augmentations module
  CHANGELOG.md
  kornia/augmentation/_2d/geometric/__init__.py
  kornia/augmentation/_2d/geometric/resize.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/resize.py
  test/augmentation/test_augmentation.py
Labels: enhancement :rocket:, module: augmentations

#1548 add resize augmentation docs and fixes
  docs/source/augmentation.base.rst
  docs/source/augmentation.module.rst
  docs/source/contrib.rst
  docs/source/references.bib
  kornia/utils/draw.py
Labels: docs :books:, P1 🚨

#1532 improve the `histogram_matching` function
  kornia/contrib/histogram_matching.py
  test/test_contrib.py
Labels: bug :bug:, P1 🚨, module: enhance

#1543 Bugfix for larger MotionBlur kernel size ranges
  CHANGELOG.md
  kornia/augmentation/_2d/intensity/motion_blur.py
  test/augmentation/test_motionblur.py
Labels: bug :bug:, P1 🚨, module: augmentations

#1510 Adding cropping option for SSIM
  kornia/losses/ssim.py
  kornia/metrics/ssim.py
Labels: enhancement :rocket:, P1 🚨, module: losses
