Repository kornia/kornia, pull requests merged in 2022-04, with the labels that each got.

#1675 Fix RandomResizedCrop bug
  kornia/augmentation/random_generator/_2d/crop.py
  kornia/augmentation/random_generator/_2d/planckian_jitter.py
Labels: bug :bug:, module: augmentations

#1674 more epipolar metrics (+`linalg` utility)
  docs/source/geometry.epipolar.rst
  docs/source/geometry.linalg.rst
  kornia/geometry/epipolar/__init__.py
  kornia/geometry/epipolar/_metrics.py
  kornia/geometry/linalg.py
  test/geometry/epipolar/test_epipolar_metrics.py
  test/geometry/test_linalg.py
Labels: enhancement :rocket:, module: geometry

#1686 [fix]receive num_features as KeyNetDetector constructor arg
  kornia/feature/integrated.py
Labels: bug :bug:, enhancement :rocket:, module: feature

#1682 [feat] Add Lovasz-Hinge/Softmax losses
  docs/source/losses.rst
  kornia/losses/__init__.py
  kornia/losses/lovasz_hinge.py
  kornia/losses/lovasz_softmax.py
  test/losses/test_losses.py
Labels: feature request, module: losses

#1687 Enhancement to Resize Augmentation
  kornia/augmentation/_2d/geometric/resize.py
Labels: enhancement :rocket:, module: augmentations

#1690 Missing `f` prefix on f-strings fix
  kornia/enhance/equalization.py
Labels: code heatlh :pill:

#1685 [feat] `adjust_sigmoid` and `adjust_log` initial implementation
  docs/source/enhance.rst
  kornia/enhance/__init__.py
  kornia/enhance/adjust.py
  test/enhance/test_adjust.py
Labels: feature request, module: enhance
