Repository kornia/kornia, pull requests merged in 2022-08, with the labels that each got.

#1811 disable accelerate for macos and pytorch 1.10.2
  kornia/x/trainer.py
  setup_dev_env.sh
  test/x/__init__.py
Labels: CI :gear:

#1818 update flake8 to 5.0.4 and fixes
  .github/workflows/tests_cpu.yml
  .pre-commit-config.yaml
  Makefile
  requirements/dev.txt
Labels: code heatlh :pill:, CI :gear:

#1801 Add Quaternion API
  docs/source/geometry.quaternion.rst
  docs/source/geometry.rst
  kornia/core/__init__.py
  kornia/core/_backend.py
  kornia/geometry/quaternion.py
  kornia/testing/__init__.py
  test/geometry/test_quaternion.py
Labels: feature request, module: geometry

#1835 Change embedded Gradio demo to use web component instead of iframe
  docs/source/gradio/enhance_gradio.html
Labels: docs :books:

#1834 fix tests and warnings
  kornia/testing/__init__.py
  test/enhance/test_normalize.py
  test/geometry/test_line.py
  test/test_contrib.py
Labels: CI :gear:
