Repository kornia/kornia, pull requests merged in 2022-02, with the labels that each got.

#1551 Adds `MS-SSIMLoss` reconstruction loss function
  docs/source/losses.rst
  kornia/losses/__init__.py
  kornia/losses/ms_ssim.py
  test/losses/test_losses.py
  test/losses/test_ssim.py
Labels: feature request, module: losses

#1571 [fix] RandomCrop fix and improvement
  kornia/augmentation/_2d/geometric/center_crop.py
  kornia/augmentation/_2d/geometric/crop.py
  kornia/augmentation/base.py
Labels: bug :bug:, module: augmentations

#1564 Fix `draw_line` produce wrong output for coordinates larger than uint8
  kornia/utils/draw.py
  test/utils/test_draw.py
Labels: bug :bug:, module: utils

#962 Add Dense SIFT
  docs/source/feature.rst
  kornia/feature/__init__.py
  kornia/feature/siftdesc.py
  test/feature/test_siftdesc.py
Labels: help wanted, wip 🛠️, feature request, P2 😅, Difficulty: easy, module: feature

#1585 making `compute_correspond_epilines` work with fundamental and point of volumetric tensors
  kornia/geometry/conversions.py
  kornia/geometry/epipolar/fundamental.py
  test/geometry/epipolar/test_fundamental.py
Labels: enhancement :rocket:, module: geometry

#1570 [fix] AugmentationSequential bbox keypoints transformation fix
  kornia/augmentation/container/utils.py
  test/augmentation/test_container.py
Labels: bug :bug:, P1 🚨, module: augmentations

#1590 [feat] deprecated `return_transform`, enabled 3D augmentations in AugmenationSequential
  kornia/augmentation/_2d/base.py
  kornia/augmentation/_2d/geometric/affine.py
  kornia/augmentation/_2d/geometric/base.py
  kornia/augmentation/_2d/geometric/center_crop.py
  kornia/augmentation/_2d/geometric/crop.py
  kornia/augmentation/_2d/geometric/elastic_transform.py
  kornia/augmentation/_2d/geometric/fisheye.py
  kornia/augmentation/_2d/geometric/horizontal_flip.py
  kornia/augmentation/_2d/geometric/pad.py
  kornia/augmentation/_2d/geometric/perspective.py
  kornia/augmentation/_2d/geometric/resize.py
  kornia/augmentation/_2d/geometric/resized_crop.py
  kornia/augmentation/_2d/geometric/rotation.py
  kornia/augmentation/_2d/geometric/thin_plate_spline.py
  kornia/augmentation/_2d/geometric/vertical_flip.py
  kornia/augmentation/_2d/intensity/base.py
  kornia/augmentation/_2d/intensity/box_blur.py
  kornia/augmentation/_2d/intensity/channel_shuffle.py
  kornia/augmentation/_2d/intensity/color_jitter.py
  kornia/augmentation/_2d/intensity/denormalize.py
  kornia/augmentation/_2d/intensity/equalize.py
  kornia/augmentation/_2d/intensity/erasing.py
  kornia/augmentation/_2d/intensity/gaussian_blur.py
  kornia/augmentation/_2d/intensity/gaussian_noise.py
  kornia/augmentation/_2d/intensity/grayscale.py
  kornia/augmentation/_2d/intensity/invert.py
  kornia/augmentation/_2d/intensity/motion_blur.py
  kornia/augmentation/_2d/intensity/normalize.py
  kornia/augmentation/_2d/intensity/posterize.py
  kornia/augmentation/_2d/intensity/sharpness.py
  kornia/augmentation/_2d/intensity/solarize.py
  kornia/augmentation/_3d/base.py
  kornia/augmentation/_3d/geometric/affine.py
  kornia/augmentation/_3d/geometric/center_crop.py
  kornia/augmentation/_3d/geometric/crop.py
  kornia/augmentation/_3d/geometric/depthical_flip.py
  kornia/augmentation/_3d/geometric/horizontal_flip.py
  kornia/augmentation/_3d/geometric/perspective.py
  kornia/augmentation/_3d/geometric/rotation.py
  kornia/augmentation/_3d/geometric/vertical_flip.py
  kornia/augmentation/_3d/intensity/equalize.py
  kornia/augmentation/_3d/intensity/motion_blur.py
  kornia/augmentation/base.py
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/image.py
  kornia/augmentation/container/patch.py
  kornia/augmentation/container/utils.py
  kornia/augmentation/container/video.py
  kornia/augmentation/utils/helpers.py
  kornia/constants.py
  kornia/geometry/transform/crop2d.py
  test/augmentation/test_augmentation.py
  test/augmentation/test_augmentation_3d.py
  test/augmentation/test_backward.py
  test/augmentation/test_backward_3d.py
  test/augmentation/test_base.py
  test/augmentation/test_container.py
  test/augmentation/test_motionblur.py
  test/augmentation/test_perspective_rand.py
Labels: enhancement :rocket:, P1 🚨, module: augmentations
