Repository kornia/kornia, pull requests merged in 2023-01, with the labels that each got.

#2124 add transparent pad to `CenterCrop` docs example
  docs/generate_example_images.py
Labels: docs :books:

#2025 Ensure support to Python 3.9 and 3.10
  .github/workflows/pr_test_cpu.yml
  .github/workflows/python_package.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/tests_nightly.yml
  setup.cfg
Labels: CI :gear:

#2127 Fix different warning and errors when building doc
  docs/generate_example_images.py
  docs/source/applications/image_denoising.rst
  docs/source/applications/image_registration.rst
  docs/source/conf.py
  docs/source/filters.rst
  docs/source/geometry.conversions.rst
  docs/source/geometry.line.rst
  docs/source/geometry.transform.rst
  docs/source/gradio/geometry_image_transform.html
  docs/source/gradio/image_registration.html
  docs/source/gradio/total_variation_denoising.html
  docs/source/index.rst
  docs/source/models/dexined.rst
  docs/source/references.bib
  kornia/augmentation/_2d/intensity/brightness.py
  kornia/augmentation/_2d/intensity/color_jitter.py
  kornia/augmentation/_2d/intensity/contrast.py
  kornia/augmentation/_2d/intensity/hue.py
  kornia/augmentation/_2d/intensity/saturation.py
  kornia/augmentation/_2d/mix/cutmix.py
  kornia/augmentation/_2d/mix/mixup.py
  kornia/augmentation/container/dispatcher.py
  kornia/enhance/adjust.py
  kornia/geometry/boxes.py
  kornia/geometry/conversions.py
  kornia/geometry/epipolar/_metrics.py
  kornia/geometry/epipolar/fundamental.py
  kornia/geometry/homography.py
  kornia/geometry/linalg.py
Labels: docs :books:

#2132 fix TensorWrapper serialization
  kornia/core/tensor_wrapper.py
  test/core/test_tensor_wrapper.py
  test/geometry/test_plane.py
Labels: bug :bug:

#2128 Run nightly CI just with labeled PR
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_nightly.yml
  README.md
  README_zh-CN.md
Labels: CI :gear:, nightly

#2137 move deps to `setup.py`
  setup.cfg
  setup.py
Labels: dependencies, nightly

#2133 move tests workflow to reusable workflow
  .github/README.md
  .github/actions/env/action.yml
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/scheduled_test_nightly.yml
  .github/workflows/scheduled_test_typing.yml
  .github/workflows/tests.yml
Labels: CI :gear:, nightly

#2140 Update `nightly` labeled condition
  .github/workflows/pr_test_cpu.yml
Labels: CI :gear:, nightly

#2145 fix adalam tests for py310
  kornia/feature/adalam/utils.py
Labels: bug :bug:, module: feature

#2146 add `fail-fast:false` as default on tests workflow
  .github/actions_info.md
  .github/workflows/tests.yml
Labels: CI :gear:, nightly

#2131 Fix params computation for `LongestMaxSize` and `SmallestMaxSize`
  kornia/augmentation/random_generator/_2d/resize.py
  test/augmentation/test_augmentation.py
Labels: bug :bug:, module: augmentations

#2159 fix doc build - `sphinx-autodoc-typehints==1.21.3`
  setup.py
Labels: bug :bug:, docs :books:, dependencies

#2152 Improve losses tests, add `TestSSIM3d`, and `BaseTester.gradcheck`
  docs/source/losses.rst
  kornia/losses/cauchy.py
  kornia/losses/charbonnier.py
  kornia/losses/geman_mcclure.py
  kornia/losses/welsch.py
  kornia/testing/__init__.py
  test/losses/test_losses.py
  test/losses/test_ssim.py
  test/test_metrics.py
Labels: docs :books:, code heatlh :pill:

#2153 modify comments of rgb and lab conversion
  kornia/color/lab.py
Labels: docs :books:, module: color

#2166 unpin `sphinx-autodoc-typehints`
  setup.py
Labels: docs :books:, dependencies

#2167 Fix docs of `boxes`, `MultiResolutionDetector`. `apply colormap`, `AugmentationSequential`
  docs/generate_example_images.py
  docs/source/color.rst
  docs/source/feature.rst
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/patch.py
  kornia/geometry/boxes.py
Labels: docs :books:

#2168 Fix output types of augmentations on autocast regions
  docs/source/utils.rst
  kornia/augmentation/_2d/base.py
  kornia/augmentation/_2d/mix/base.py
  kornia/augmentation/base.py
  kornia/augmentation/container/augment.py
  kornia/geometry/boxes.py
  kornia/geometry/keypoints.py
  kornia/utils/__init__.py
  kornia/utils/helpers.py
  kornia/utils/misc.py
  test/augmentation/test_base.py
  test/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2177 Fix planckian jitter for cuda
  kornia/augmentation/_2d/intensity/planckian_jitter.py
  test/augmentation/test_augmentation.py
Labels: bug :bug:, module: augmentations

#2179 [enhance] improve flipping and cropping speed
  kornia/augmentation/_2d/geometric/crop.py
  kornia/geometry/transform/flips.py
Labels: enhancement :rocket:

#2120 Replace jit test method in favor of dynamo in `BaseTester`
  .github/workflows/pr_test_cpu.yml
  conftest.py
  kornia/testing/__init__.py
  test/color/test_gray.py
Labels: enhancement :rocket:, jit, nightly
