Repository kornia/kornia, pull requests merged in 2023-10, with the labels that each got.

#2591 drop `torchvision` from docs deps
  requirements/requirements-docs.txt
Labels: docs :books:, dependencies, code heatlh :pill:

#2598 Update readthedocs.yml
  readthedocs.yml
Labels: docs :books:

#2587 [speed up CI tests suite] Skip slow tests as default
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/tests.yml
  conftest.py
  pyproject.toml
  requirements/requirements-dev.txt
  test/augmentation/test_augmentation.py
  test/augmentation/test_container.py
  test/augmentation/test_motionblur.py
  test/color/test_gray.py
  test/contrib/models/test_rt_detr.py
  test/contrib/models/test_sam.py
  test/contrib/models/test_tiny_vit.py
  test/contrib/test_contrib.py
  test/contrib/test_prompter.py
  test/enhance/test_adjust.py
  test/feature/test_defmo.py
  test/feature/test_disk.py
  test/feature/test_hardnet.py
  test/feature/test_integrated.py
  test/feature/test_loftr.py
  test/feature/test_matching.py
  test/feature/test_sold2.py
  test/feature/test_tfeat.py
  test/filters/test_filters.py
  test/geometry/test_ransac.py
  test/geometry/transform/test_image_registrator.py
  test/image/test_image.py
  test/integration/test_soft_argmax2d.py
  test/nerf/test_nerf_solver.py
  test/tracking/test_planar_tracking.py
  test/x/test_detection.py
  test/x/test_image_classification.py
  test/x/test_segmentation.py
Labels: dependencies, CI :gear:

#2593 drop `cv2` as dev dependency
  requirements/requirements-dev.txt
  test/io/test_io_image.py
Labels: dependencies

#2605 bump pytorch version to 2.1.0
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/test_typing.yml
  .github/workflows/tests.yml
  kornia/augmentation/auto/operations/base.py
  kornia/augmentation/auto/operations/policy.py
  kornia/augmentation/container/augment.py
  kornia/feature/lightglue.py
  test/augmentation/test_container.py
  test/contrib/models/test_tiny_vit.py
  test/filters/test_guided.py
  test/geometry/transform/test_crop3d.py
  test/integration/test_focal.py
Labels: CI :gear:

#2606 Ensure python 3.11 support
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/scheduled_test_nightly.yml
  .github/workflows/scheduled_test_pypi_package.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/test_typing.yml
  .github/workflows/tests.yml
Labels: code heatlh :pill:, CI :gear:

#2621 skip dynamo test for py311 torch 2.0.x
  conftest.py
Labels: code heatlh :pill:, CI :gear:

#2620 expose `average_endpoint_error` metric
  kornia/metrics/__init__.py
  test/test_metrics.py
Labels: code heatlh :pill:

#2624 Update docs CI
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/docs.yml
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
Labels: docs :books:, CI :gear:

#2580 Add differentiable 5PC (five point algorithm) for essential matrix estimation
  docs/source/geometry.epipolar.rst
  docs/source/geometry.solvers.rst
  docs/source/references.bib
  kornia/geometry/epipolar/__init__.py
  kornia/geometry/epipolar/essential.py
  kornia/geometry/solvers/__init__.py
  kornia/geometry/solvers/polynomial_solver.py
  test/geometry/epipolar/test_essential.py
Labels: feature request, module: geometry

#2614 add RandomClahe
  docs/source/augmentation.module.rst
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/clahe.py
  kornia/augmentation/__init__.py
  kornia/enhance/equalization.py
  test/augmentation/test_augmentation.py
Labels: feature request, module: augmentations

#2482 [feat] Add NamedPose
  kornia/geometry/__init__.py
  kornia/geometry/liegroup/se2.py
  kornia/geometry/liegroup/se3.py
  kornia/geometry/pose.py
  test/geometry/test_pose.py
Labels: feature request, module: geometry

#2629 [feat] Raw to rgb conversion with downscaling
  docs/source/color.rst
  kornia/color/__init__.py
  kornia/color/raw.py
  test/color/test_raw.py
Labels: feature request, module: color

#2631 feat: LightGlue-ONNX
  docs/source/feature.rst
  kornia/feature/__init__.py
  kornia/feature/lightglue_onnx/__init__.py
  kornia/feature/lightglue_onnx/lightglue.py
  kornia/feature/lightglue_onnx/utils/__init__.py
  kornia/feature/lightglue_onnx/utils/download.py
  kornia/feature/lightglue_onnx/utils/keypoints.py
  requirements/requirements-dev.txt
  test/feature/test_lightglue_onnx.py
Labels: feature request

#2634 Drop `scipy` from dev dependencies
  conftest.py
  docker/Dockerfile
  requirements/requirements-dev.txt
  test/losses/test_hd.py
Labels: dependencies
