Repository kornia/kornia, pull requests merged in 2023-02, with the labels that each got.

#2197 Move padding_size to device in pad for boxes
  kornia/geometry/boxes.py
Labels: bug :bug:, module: augmentations

#2196 Return boxes tensor directly if no boxes
  kornia/geometry/boxes.py
  test/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2192 The isinstance checks order are inverted
  kornia/metrics/psnr.py
Labels: module: metrics

#2178 Skip `x` tests for `torch=1.12.1` and `accelerate` not available
  test/x/test_detection.py
  test/x/test_image_classification.py
  test/x/test_segmentation.py
Labels: bug :bug:, module: trainer

#2191 Drop some ci job
  .github/workflows/pr_test_cpu.yml
  .github/workflows/pr_test_typing.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/scheduled_test_nightly.yml
  .github/workflows/scheduled_test_typing.yml
Labels: CI :gear:

#2195 Make value an attribute of RandomErasing instances again
  kornia/augmentation/_2d/intensity/erasing.py
Labels: bug :bug:, module: augmentations

#2199 Run CI to just test fp64 on ubuntu and nightly run dynamo tests on PR's
  .github/actions_info.md
  .github/workflows/pr_test_cpu.yml
  .github/workflows/tests.yml
Labels: CI :gear:, nightly

#2187 Small refactor on `filters` module: Dropping JIT support
  kornia/augmentation/_2d/intensity/gaussian_blur.py
  kornia/augmentation/random_generator/_2d/gaussian_blur.py
  kornia/filters/__init__.py
  kornia/filters/blur.py
  kornia/filters/blur_pool.py
  kornia/filters/canny.py
  kornia/filters/dexined.py
  kornia/filters/filter.py
  kornia/filters/gaussian.py
  kornia/filters/kernels.py
  kornia/filters/kernels_geometry.py
  kornia/filters/laplacian.py
  kornia/filters/median.py
  kornia/filters/motion.py
  kornia/filters/sobel.py
  kornia/filters/unsharp.py
  kornia/geometry/transform/elastic_transform.py
  kornia/testing/__init__.py
  kornia/utils/__init__.py
  kornia/utils/helpers.py
  test/augmentation/test_augmentation.py
  test/feature/test_affine_shape_estimator.py
  test/feature/test_keynet.py
  test/feature/test_mkd.py
  test/feature/test_responces_local_features.py
  test/filters/test_blur.py
  test/filters/test_blur_pool.py
  test/filters/test_canny.py
  test/filters/test_filters.py
  test/filters/test_gaussian.py
  test/filters/test_hanning.py
  test/filters/test_laplacian.py
  test/filters/test_median.py
  test/filters/test_motion.py
  test/filters/test_sobel.py
  test/filters/test_unsharp_mask.py
  test/geometry/transform/test_elastic_transform.py
  test/geometry/transform/test_pyramid.py
  test/losses/test_ssim.py
  test/test_metrics.py
Labels: jit, module: filters, nightly

#2210 Replace `assert_allclose` by `assert_close`
  kornia/enhance/adjust.py
  test/augmentation/test_dist_mapper.py
  test/geometry/calibration/test_undistort.py
  test/geometry/camera/test_stereo.py
  test/geometry/test_bbox.py
  test/geometry/test_boxes.py
  test/grad_estimator/test_ste.py
Labels: code heatlh :pill:

#2209 Fix random crop for keypoints on CUDA device
  kornia/augmentation/_2d/geometric/crop.py
Labels: bug :bug:, module: augmentations

#2204 Remove py 3.7 for nightly CI
  .github/workflows/scheduled_test_nightly.yml
Labels: CI :gear:, nightly

#2215 Fix CUDA failling tests of same device on `Augmentations`
  kornia/augmentation/auto/operations/base.py
  kornia/augmentation/random_generator/_2d/cutmix.py
Labels: bug :bug:, module: augmentations

#2217 Update contributing guide
  CONTRIBUTING.md
  CONTRIBUTING.rst
Labels: code heatlh :pill:

#2219 Drop JIT support for `core.check`, `Boxes`, and some others
  kornia/core/check.py
  kornia/geometry/bbox.py
  kornia/geometry/boxes.py
  kornia/geometry/calibration/undistort.py
  kornia/geometry/linalg.py
  kornia/geometry/transform/homography_warper.py
  kornia/geometry/transform/imgwarp.py
  kornia/geometry/transform/pyramid.py
  kornia/losses/__init__.py
  kornia/losses/cauchy.py
  kornia/losses/charbonnier.py
  kornia/losses/depth_smooth.py
  kornia/losses/dice.py
  kornia/losses/divergence.py
  kornia/losses/focal.py
  kornia/losses/geman_mcclure.py
  kornia/losses/hausdorff.py
  kornia/losses/lovasz_hinge.py
  kornia/losses/lovasz_softmax.py
  kornia/losses/ms_ssim.py
  kornia/losses/psnr.py
  kornia/losses/ssim.py
  kornia/losses/ssim3d.py
  kornia/losses/total_variation.py
  kornia/losses/tversky.py
  kornia/losses/welsch.py
  test/color/test_colormap.py
  test/enhance/test_adjust.py
  test/enhance/test_core.py
  test/geometry/calibration/test_undistort.py
  test/geometry/test_bbox.py
  test/geometry/test_conversions.py
  test/geometry/test_linalg.py
  test/geometry/transform/test_crop2d.py
  test/geometry/transform/test_crop3d.py
  test/geometry/transform/test_homography_warper.py
  test/geometry/transform/test_imgwarp.py
  test/geometry/transform/test_pyramid.py
  test/losses/test_losses.py
Labels: jit, module: core, nightly

#2225 PEP621: Move more configuration into pyproject.toml
  .flake8
  .pre-commit-config.yaml
  kornia/feature/loftr/utils/coarse_matching.py
  pyproject.toml
  setup.cfg
  setup.py
Labels: dependencies, code heatlh :pill:

#2232 Clean up metadata and fix requirements
  .pre-commit-config.yaml
  examples/train/image_classifier/requirements.txt
  examples/train/object_detection/requirements.txt
  examples/train/semantic_segmentation/requirements.txt
  kornia/__init__.py
  kornia/utils/_compat.py
  packaging/README.rst
  packaging/build_wheel.sh
  pyproject.toml
  requirements/requirements-dev.txt
  requirements/requirements-docs.txt
  requirements/requirements-x.txt
  requirements/requirements.txt
  test/augmentation/test_auto_operation.py
  test/color/test_hls.py
  test/color/test_raw.py
  test/enhance/test_histogram.py
  test/nerf/test_data_utils.py
  test/nerf/test_nerf_solver.py
Labels: dependencies, code heatlh :pill:

#2229 Feat/random snow
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/random_snow.py
  kornia/augmentation/__init__.py
  test/augmentation/test_augmentation.py
Labels: feature request, module: augmentations
