Repository kornia/kornia, pull requests merged in 2023-11, with the labels that each got.

#2628 Rename variables shadowing build-in input function
  kornia/losses/dice.py
  kornia/losses/divergence.py
  kornia/losses/focal.py
  kornia/losses/psnr.py
  kornia/losses/tversky.py
  kornia/metrics/accuracy.py
  kornia/metrics/confusion_matrix.py
  kornia/metrics/mean_iou.py
  kornia/metrics/psnr.py
  kornia/testing/__init__.py
  test/losses/test_losses.py
Labels: code heatlh :pill:

#2636 add deprecated decorator `depth_to_3d`
  kornia/geometry/depth.py
Labels: code heatlh :pill:

#2607 Add EfficientViT model
  docs/source/contrib.rst
  docs/source/index.rst
  docs/source/models/efficient_vit.rst
  kornia/contrib/models/efficient_vit/__init__.py
  kornia/contrib/models/efficient_vit/backbone.py
  kornia/contrib/models/efficient_vit/model.py
  kornia/contrib/models/efficient_vit/nn/__init__.py
  kornia/contrib/models/efficient_vit/nn/act.py
  kornia/contrib/models/efficient_vit/nn/norm.py
  kornia/contrib/models/efficient_vit/nn/ops.py
  kornia/contrib/models/efficient_vit/utils/__init__.py
  kornia/contrib/models/efficient_vit/utils/list.py
  kornia/contrib/models/efficient_vit/utils/network.py
  test/contrib/models/test_efficient_vit.py
Labels: feature request, module: contrib

#2667 Bump pytorch to 2.1.1
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/docs.yml
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/test_typing.yml
  .github/workflows/tests.yml
  test/filters/test_canny.py
  test/filters/test_guided.py
Labels: CI :gear:

#2670 move onnxruntime to `x` requirements
  requirements/requirements-dev.txt
  requirements/requirements-x.txt
Labels: dependencies, code heatlh :pill:
