Repository kornia/kornia, pull requests merged in 2024-03, with the labels that each got.

#2794 Refactor and add more palettes of colormaps
  docs/generate_examples.py
  docs/source/color.rst
  kornia/color/__init__.py
  kornia/color/_colormap_data.py
  kornia/color/colormap.py
  tests/color/test_colormap.py
Labels: enhancement :rocket:, module: color

#2823 feat: RandomLinearIllumination and RandomLinearCornerIllumination
  docs/generate_examples.py
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/linear_illumination.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/linear_illumination.py
  tests/augmentation/test_augmentation.py
Labels: feature request, module: augmentations

#2827 fix (docs): add `RandomLinearIllumination` and `RandomLinearCornerIll…
  docs/source/augmentation.module.rst
Labels: docs :books:

#2825 ColorMap tests coverage
  tests/color/test_colormap.py
  tests/contrib/models/test_rt_detr.py
  tests/feature/test_affine_shape_estimator.py
Labels: code heatlh :pill:

#2800 feat: augmentation sequential supports mask (B, H, W) with images (B, C, H, W)
  kornia/augmentation/_2d/base.py
  kornia/augmentation/_2d/mix/base.py
  kornia/augmentation/_3d/base.py
  kornia/augmentation/base.py
  kornia/augmentation/utils/__init__.py
  kornia/augmentation/utils/helpers.py
  tests/augmentation/test_augmentation.py
  tests/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2833 CI: ensure pytorch 2.2.1 support
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
Labels: code heatlh :pill:, CI :gear:

#2844 Pre commit update hooks
  .pre-commit-config.yaml
  kornia/augmentation/auto/autoaugment/ops.py
  kornia/augmentation/auto/rand_augment/ops.py
  kornia/color/lab.py
  kornia/color/luv.py
  kornia/contrib/classification.py
  kornia/contrib/models/rt_detr/architecture/resnet_d.py
  kornia/contrib/models/sam/architecture/common.py
  kornia/contrib/models/sam/architecture/image_encoder.py
  kornia/contrib/models/sam/architecture/mask_decoder.py
  kornia/contrib/models/sam/architecture/prompt_encoder.py
  kornia/contrib/models/sam/architecture/transformer.py
  kornia/contrib/models/sam/model.py
  kornia/contrib/vit.py
  kornia/core/check.py
  kornia/feature/hardnet.py
  kornia/feature/sold2/backbones.py
  kornia/geometry/camera/distortion_affine.py
  kornia/geometry/camera/projection_orthographic.py
  kornia/geometry/camera/projection_z1.py
  kornia/geometry/depth.py
  kornia/geometry/epipolar/essential.py
  kornia/geometry/epipolar/projection.py
  kornia/geometry/epipolar/scene.py
  kornia/geometry/liegroup/se2.py
  kornia/geometry/liegroup/so2.py
  kornia/geometry/ransac.py
  kornia/geometry/solvers/polynomial_solver.py
  kornia/geometry/subpix/dsnt.py
  kornia/geometry/transform/homography_warper.py
  kornia/geometry/transform/image_registrator.py
  kornia/geometry/transform/imgwarp.py
  kornia/testing/__init__.py
  kornia/utils/_compat.py
  kornia/utils/helpers.py
  kornia/utils/image_print.py
  kornia/x/trainer.py
  tests/contrib/models/test_rt_detr.py
  tests/contrib/models/test_sam.py
  tests/contrib/models/test_tiny_vit.py
  tests/contrib/test_prompter.py
  tests/filters/test_filters.py
  tests/filters/test_laplacian.py
  tests/filters/test_motion.py
  tests/filters/test_unsharp_mask.py
Labels: code heatlh :pill:

#2849 fix: typing ignore for `dedode.tranformer`
  pyproject.toml
Labels: code heatlh :pill:, module: feature

#2846 Fix datakey retreival for BBOX_XYWH and BBOX_XYXY
  kornia/augmentation/container/augment.py
  tests/augmentation/test_container.py
Labels: bug :bug:, module: augmentations

#2850 Fix: DeDoDe tests coverage
  kornia/feature/dedode/dedode.py
  tests/feature/test_dedode.py
Labels: code heatlh :pill:, module: feature

#2858 fix: dedode pretained type ignore dedode init
  kornia/feature/dedode/dedode.py
Labels: code heatlh :pill:, CI :gear:

#2861 added kornia's euclidian_distance function in kmeans algorithm
  kornia/contrib/kmeans.py
  kornia/geometry/linalg.py
Labels: enhancement :rocket:, module: contrib

#2853 feat: 2d augmentation benchmarks
  CONTRIBUTING.md
  Makefile
  benchmarks/augmentation/2d_geometric_test.py
  benchmarks/augmentation/2d_intensity_test.py
  benchmarks/augmentation/conftest.py
  benchmarks/color/gray_test.py
  conftest.py
  docker/Dockerfile.benchmark
  docs/source/augmentation.module.rst
  kornia/augmentation/_2d/geometric/perspective.py
  kornia/augmentation/_2d/geometric/resize.py
  kornia/augmentation/_2d/geometric/resized_crop.py
  kornia/augmentation/_2d/intensity/brightness.py
  kornia/augmentation/_2d/intensity/color_jitter.py
  kornia/augmentation/_2d/intensity/contrast.py
  kornia/augmentation/_2d/intensity/hue.py
  kornia/augmentation/_2d/intensity/planckian_jitter.py
  kornia/augmentation/_2d/intensity/random_rain.py
  requirements/requirements-dev.txt
  tests/augmentation/test_augmentation.py
  tests/contrib/test_prompter.py
Labels: code heatlh :pill:
