Repository kornia/kornia, pull requests merged in 2024-04, with the labels that each got.

#2856 Support instance masks (N,H,W)
  kornia/augmentation/container/ops.py
  kornia/augmentation/utils/helpers.py
  tests/augmentation/test_container.py
Labels: feature request, module: augmentations

#2859 Feat: random channel dropout
  benchmarks/augmentation/2d_intensity_test.py
  docs/generate_examples.py
  docs/source/augmentation.module.rst
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/channel_dropout.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/channel_dropout.py
  tests/augmentation/test_augmentation.py
Labels: feature request, module: augmentations

#2872 fix [aug]: gaussian blur compile and compile tests skips
  kornia/augmentation/_2d/intensity/gaussian_blur.py
  tests/augmentation/test_augmentation.py
Labels: bug :bug:, module: augmentations, code heatlh :pill:

#2871 Fixes the use of the gtag extension
  docs/source/conf.py
Labels: bug :bug:, docs :books:

#2870 remove unused dependencies
  Makefile
  docker/Dockerfile.benchmark
  requirements/requirements-dev.txt
Labels: dependencies, code heatlh :pill:

#2874 fix: skip dynamo test for visual prompter
  conftest.py
  tests/contrib/test_prompter.py
Labels: bug :bug:

#2879 adds weight parameter to dice and lovasz_softmax losses
  kornia/losses/dice.py
  kornia/losses/lovasz_softmax.py
  tests/losses/test_dice.py
  tests/losses/test_lovaz_softmax.py
Labels: enhancement :rocket:, module: losses

#2888 bump: workflows to 1.8.1 and torch to 2.2.2
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
Labels: CI :gear:
