Repository kornia/kornia, pull requests merged in 2024-02, with the labels that each got.

#2777 Introduces `benchmarks/`
  benchmarks/color/gray_test.py
  pyproject.toml
  requirements/requirements-benchmarks.txt
Labels: feature request, dependencies, code heatlh :pill:

#2786 ViT: Load Jax augreg weights
  docs/source/contrib.rst
  kornia/contrib/vit.py
  tests/contrib/test_contrib.py
Labels: enhancement :rocket:, module: contrib

#2796 docs: add not-found option
  docs/source/conf.py
  requirements/requirements-docs.txt
Labels: docs :books:, dependencies

#2740 Feat: Support list of masks in `AugmentationSequential`
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/ops.py
  tests/augmentation/test_container.py
Labels: feature request, module: augmentations

#2797 test suite: skip fp64 canny dynamo test
  tests/filters/test_canny.py
Labels: enhancement :rocket:

#2802 Test suite: separate contrib tests into individual files
  tests/contrib/test_classification_head.py
  tests/contrib/test_combine_tensor_patch.py
  tests/contrib/test_connected_component.py
  tests/contrib/test_contrib.py
  tests/contrib/test_conv_distance_transformer.py
  tests/contrib/test_diamond_square.py
  tests/contrib/test_edge_detector.py
  tests/contrib/test_extract_tensor_patch.py
  tests/contrib/test_face_detection.py
  tests/contrib/test_hist_match.py
  tests/contrib/test_image_stitcher.py
  tests/contrib/test_lambda_module.py
  tests/contrib/test_mobile_vit.py
  tests/contrib/test_object_detector.py
  tests/contrib/test_vision_transformer.py
Labels: code heatlh :pill:

#2780 Feat: add Gradient Illumination augmentations (gaussian)
  docs/generate_examples.py
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/gaussian_illumination.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/gaussian_illumination.py
  kornia/filters/kernels.py
  tests/augmentation/test_augmentation.py
  tests/filters/test_gaussian.py
Labels: feature request, module: augmentations

#2803 feat: Add RandomJPEG Augmentation
  docs/generate_examples.py
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/jpeg.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/jpeg.py
  tests/augmentation/test_augmentation.py
Labels: feature request, module: augmentations

#2795 Add: differentiable clipping, floor and rounding functions
  kornia/enhance/jpeg.py
  kornia/utils/__init__.py
  kornia/utils/misc.py
  tests/utils/test_misc.py
Labels: enhancement :rocket:, module: utils

#2804 [feat] KMeans implementation
  docs/source/contrib.rst
  kornia/contrib/__init__.py
  kornia/contrib/kmeans.py
  tests/contrib/test_kmeans.py
Labels: feature request, module: contrib

#2799 Aug: Add simple support to dict for AugSequential
  kornia/augmentation/container/augment.py
  kornia/augmentation/container/ops.py
  tests/augmentation/test_container.py
  tests/contrib/test_prompter.py
Labels: enhancement :rocket:, module: augmentations

#2814 remove image prompter in favor of visual prompter
  kornia/contrib/image_prompter.py
Labels: code heatlh :pill:
