Repository kornia/kornia, pull requests merged in 2024-01, with the labels that each got.

#2727 Replace docs source link from `viewcode` to github
  docs/source/conf.py
Labels: enhancement :rocket:, docs :books:

#2729 Bump readthedocs python version
  docs/source/conf.py
  readthedocs.yml
Labels: enhancement :rocket:, docs :books:

#2735 Fixes `extract_tensor_patches` to work with partial patches cases
  kornia/contrib/extract_patches.py
  test/contrib/test_contrib.py
Labels: bug :bug:, module: contrib

#2742 bump torch `2.1.2`
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/docs.yml
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/test_typing.yml
  .github/workflows/tests.yml
  test/filters/test_canny.py
  test/filters/test_guided.py
Labels: CI :gear:

#2744 remove retrigger CI on PR's when labeled
  .github/workflows/pr_test_cpu.yml
Labels: enhancement :rocket:, CI :gear:

#2746 Add salt and pepper noise with docs and tests
  docs/generate_examples.py
  kornia/augmentation/_2d/intensity/__init__.py
  kornia/augmentation/_2d/intensity/salt_pepper_noise.py
  kornia/augmentation/__init__.py
  kornia/augmentation/random_generator/_2d/__init__.py
  kornia/augmentation/random_generator/_2d/salt_pepper_noise.py
  tests/augmentation/test_augmentation.py
Labels: module: augmentations

#2760 feat: differentiable jpeg
  docs/generate_examples.py
  docs/source/enhance.rst
  docs/source/references.bib
  kornia/enhance/__init__.py
  kornia/enhance/jpeg.py
  tests/enhance/test_jpeg.py
Labels: enhancement :rocket:, feature request

#2756 [CI] split coverage into multiple jobs
  .github/actions/env/action.yml
  .github/actions_info.md
  .github/workflows/docs.yml
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  .github/workflows/scheduled_test_cpu_half.yml
  .github/workflows/scheduled_test_nightly.yml
  .github/workflows/test_tutorials.yml
  .github/workflows/test_typing.yml
  .github/workflows/tests.yml
Labels: code heatlh :pill:, CI :gear:

#2763 Ci: fix old torch install
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  kornia/contrib/models/rt_detr/architecture/hybrid_encoder.py
  kornia/contrib/models/rt_detr/architecture/rtdetr_head.py
  kornia/enhance/jpeg.py
  requirements/requirements-dev.txt
  requirements/requirements-x.txt
  tests/augmentation/test_auto_operation.py
  tests/geometry/camera/test_projections.py
  tests/nerf/test_renderer.py
Labels: dependencies, CI :gear:

#2762 RandomSaltAndPepperNoise: Update algorithm to use indexing
  kornia/augmentation/_2d/intensity/salt_pepper_noise.py
  kornia/augmentation/random_generator/_2d/salt_pepper_noise.py
Labels: enhancement :rocket:, module: augmentations

#2770 skip unsupported tests cases for torch==1.9.1
  tests/contrib/models/test_efficient_vit.py
  tests/feature/test_lightglue_onnx.py
  tests/feature/test_matching.py
Labels: code heatlh :pill:

#2765 remove typing report
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  requirements/requirements-dev.txt
Labels: dependencies, code heatlh :pill:

#2772 Ensure support to `torch==2.2.0`
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  kornia/contrib/models/rt_detr/architecture/hybrid_encoder.py
Labels: dependencies, code heatlh :pill:, CI :gear:, device:mps
