Repository kornia/kornia, pull requests merged in 2024-05, with the labels that each got.

#2880 Change sold2 detector config to dataclass
  kornia/feature/sold2/sold2.py
  kornia/feature/sold2/sold2_detector.py
  kornia/utils/__init__.py
  kornia/utils/helpers.py
Labels: enhancement :rocket:, module: feature

#2912 chore (CI): ensure support to pytorch 2.3.0
  .github/workflows/pr_test_cpu.yml
  .github/workflows/scheduled_test_cpu.yml
  tests/filters/test_in_range.py
  tests/geometry/transform/test_homography_warper.py
Labels: CI :gear:

#2886 feat: support batched and float data in apply colormap
  docs/generate_examples.py
  kornia/color/colormap.py
  tests/color/test_colormap.py
Labels: enhancement :rocket:, module: color
